### ISSUE TITLE
I can't see action 'Deploy AMBA' in Github actions

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/azure-monitor-baseline-alerts#102]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi, 

In my (forked) github repo I cannot see action "Deploy AMBA" in Github actions

Instruction/Article:
Page: https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-with-GitHub-Actions/

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/d0412b40-15f9-471d-8e3f-80071c1d24ca)

In the above picture it says to 'Go to GitHub actions and run the action Deploy AMBA'
When I go to the 'Actions' in Github Actions I don't see the action Deploy AMBA 
Instead I'm seeing this:

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/5b4859e5-7f20-40e8-92c7-a07a7de711f8)

Am I doing something wrong or looking at the wrong place?
Does action 'Deploy AMBA' refers to a workflow which has to be run?

**Comment by jerrolmossel** [comment]
Hi Bruno,
Thank you. This would be highly appreciated because we're stuck at the moment.

Will the Azure pipelines deployement documentation also be updated? I also tried that deployment method when I saw it had been added.

When I'm looking now I see updates for both deployment methods since the last time I looked.
https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-with-GitHub-Actions/
https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-with-Azure-Pipelines/

Please let me know when documentation is updated.
BR,


________________________________
Van: Bruno Gabrielli ***@***.***>
Verzonden: woensdag 14 februari 2024 11:48
Aan: Azure/azure-monitor-baseline-alerts ***@***.***>
CC: jerrolmossel ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Azure/azure-monitor-baseline-alerts] I can't see action 'Deploy AMBA' in Github actions (Issue #102)


Hello @jerrolmossel<https://github.com/jerrolmossel> ,
I am planning for a documentation update that should include the missing step to create the workflow and have the Deploy AMBA appearing under the available actions.

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
documentation update is on the way. It will not contain any update for the Azure pipeline method since we did not get any issue so far. Feel free to create a new issue for it, should it be the case.

Thanks,
Bruno.
