### ISSUE TITLE
[Question/Feedback]: Ability to customise/filter Service Health Alerts without config drift?

### ISSUE THREAD

**Issue by riosengineer** [Azure/azure-monitor-baseline-alerts#103]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hey team, 

We have a lot of customers and want to adopt AMBA on a wider scale as a baseline rollout for our ALZ alerts. However, we are seeing a potential issue with a lot of noise on the service health alerts as we'll get notifications for all types even if they are not relevant for that customer.

I've checked the param file and it doesn't seem like there is currently a way to filter the service health alerts to specific regions, and services which would be beneficial for this. 

I can only find the custom deployments information which may have some use for us but we wanted to try and avoid config drift from the project if possible (and amending the policies seems the only way?).  https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-only-Service-Health-Alerts/#custom-deployment 

If there is no easy way to limit the service health alerts to a specific region(s) and/or Azure services for the individual deployments via params, then it would be nice to have some easy mechanism to do so without having major config drift.

If anyone has insight for how they're doing this with AMBA, that would be welcomed to learn about also! Thank you!

**Comment by paulgrimley** [comment]
Hi @riosengineer thanks for raising this and its not a new ask we've had which we addressed here https://github.com/Azure/alz-monitor/issues/234#issuecomment-1678504000. 

Based on this does this address your question as it only alerts on resources that are deployed and alerted on regions to which the resource is located

**Comment by riosengineer** [comment]
> Hi @riosengineer thanks for raising this and its not a new ask we've had which we addressed here [Azure/alz-monitor#234 (comment)](https://github.com/Azure/alz-monitor/issues/234#issuecomment-1678504000).
> 
> Based on this does this address your question as it only alerts on resources that are deployed and alerted on regions to which the resource is located

Thanks @paulgrimley. Apologies, I didn't see that issue when scanning the issues. I've taken a read now and it makes sense for the region filtering so I'm happy with this. 

My second query around service types seems like it's not strictly AMBA related so may have to take that up with Azure Support. For example, we had an alert for 'Azure Portal - Incorrect pricing display for Linux Virtual Machines' but the customer environment didn't have any virtual machines. 

Thanks for linking the info, will take this away.
