### ISSUE TITLE
[Question/Feedback]: No action group deployed when remediating policies.

### ISSUE THREAD

**Issue by stateofthearb** [Azure/azure-monitor-baseline-alerts#106]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I have deployed AMBA from your GitHub Repo with the PowerShell pattern. When I remediate policies, it creates the alert rules BUT it doesn't create an action group for these. I'm a bit confused as I have followed the instructions from your GitHub pages & updated the parameter file & then deploying AMBA with:

 "New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location -TemplateUri "https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json" -TemplateParameterFile ".\patterns\alz\alzArm.param.json"

The Policies/Initiatives are deployed & assigned. When remediating the RG/tags & alert rules are created BUT no action group deployed & linked to alert rules. I have added my email address to the ALZMonitorActionGroupEmail parameter.

Is there another step that I'm missing?

**Comment by paulgrimley** [comment]
Hi @stateofthearb, can you check you are deploying the latest release as we addressed a bug with this in an earlier release. There is guidance on doing so here https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Update-to-new-Release/ cc @Brunoga-MS

**Comment by stateofthearb** [comment]
Hi @paulgrimley, yes, I have tried with the latest fork as well as deploying straight from your repo with https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json.

In both cases I get the same result.

**Comment by Brunoga-MS** [comment]
Hi @stateofthearb ,
could you please share a screenshot with the result? Share also the remediation task outcome.

Thanks.

**Comment by Brunoga-MS** [comment]
Hello @stateofthearb,
any news about this one? Could you please share a screenshot with the result? Share also the remediation task outcome.

Thanks.
