### ISSUE TITLE
[Question/Feedback]: Add severity as a additional parameter of Alert name

### ISSUE THREAD

**Issue by kamil-makowski** [Azure/azure-monitor-baseline-alerts#116]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

After some test of this solution I can't see possibility to run same type of alert (ex. CPU usage) with 2 severities for the same resource, ex. 70% generate Warning alert and 90% will generate Critical one.

Is it possible to make any modification in Policy Definitions  and add severity as a part of concat function for name attribute?

**Comment by Brunoga-MS** [comment]
Hello @kamil-makowski,
thanks for your feedback. Technically speaking it is possible. any specific reason why you would need that? you can clone any existing alert, change the threshold and give it a name which include the priority should you need to create a similar one. Is this the scenario you are aiming at?

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @kamil-makowski,
any news about this one?

Thanks,
Bruno.

**Comment by kamil-makowski** [comment]
Hello @Brunoga-MS,
thank you for the reply. What do you mean as a clone of existing alert? Like manual copy in the portal?
I was checking code a bit and there are needed some changes to be able to create Azure Policies which allows deploy different severities.
I'd like to push everything with from AMBA deployment and get Azure Policy for both severities on all types of resources.

**Comment by Brunoga-MS** [comment]
Hello @kamil-makowski,
duplicating all the alerts to accomodate the severity will have multiple drawbacks among which:

- the limit on number of parameters per policy (500 per policy initiative)
- the alert and the notification storm
- the value of warning alerts that most of the customers simply ignore or do not take action upon

For the above reasons we recommend you to clone the repo and make your duplicated policy as per need. Do keep in mind the parameter number limits above.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @kamil-makowski ,
given the above explanation I am going to close this issue. Should you need more help fell free to reopen it or to create a new one.

Thanks,
Bruno.
