### ISSUE TITLE
[Question/Feedback]: AMBA & EPAC

### ISSUE THREAD

**Issue by RossCavanagh** [Azure/azure-monitor-baseline-alerts#12]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

To start with, awesome job, I only came across this from watching the most recent ALZ community call recording and have been very impressed with what has been setup!

Recently within our ogranisation we began to implement the Enterprise Policy as Code (EPAC) project, and first thing I did was import the ALZ polices. Are there plans to also add this to EPAC at all so I could quite easily use that as my source of ALZ policy truth with the ease factor or pulling in any updates now and then directly to EPAC?

Again, happy to find this project, immediately bookmarked / starred and will be keeping a close eye on it!

**Comment by paulgrimley** [comment]
Hi @RossCavanagh thanks for the feedback and great question, in fact I was speaking to the EPAC team only 2 days ago and made them aware of the repo changes. You'll need to file this ask in their repo aka.ms/epac to track progress as it is something they will need to do to support AMBA.

**Comment by kewalaka** [comment]
This project, which was used to sync the _previous_ alz monitor repository to the EPAC structure:

https://github.com/anwather/alz-monitor-extraction/

The general concept looks sound, however things have moved around a bit so it would need a bit of updating.

Might be useful as a starting point.

Also commenting so I don't forget about this project & lose it (like I almost just did 😂)
