### ISSUE TITLE
[Question/Feedback]: Stop deploying email action if the parameter is empty

### ISSUE THREAD

**Issue by jaywithersbrewin** [Azure/azure-monitor-baseline-alerts#126]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi!

If I omit `ALZMonitorActionGroupEmail` within `policyAssignmentParametersNotificationAssets` in alzArm.param.json (because I don't want notifications by email), then an email notification to `action@mail.com` is still configured in the action group.

Is it possible to stop this from happening?

Thanks!

**Comment by jaywithersbrewin** [comment]
hey @Brunoga-MS.

I only want to use `ALZWebhookServiceUri`.

Thanks!

**Comment by Brunoga-MS** [comment]
Perfect. I will investigate.

**Comment by jaywithersbrewin** [comment]
> Perfect. I will investigate.

Thanks!

**Comment by Brunoga-MS** [comment]
Hello @jaywithersbrewin ,
as a quick update, we are working on a solution to allow empty email address parameter so it will not deploy any email action with bogus addresses when not needed.

As soon as the code is ready, the merging of the corresponding PR will close this issue and you will get a notification.

Thanks,
Bruno.

**Comment by jaywithersbrewin** [comment]
> Hello @jaywithersbrewin , as a quick update, we are working on a solution to allow empty email address parameter so it will not deploy any email action with bogus addresses when not needed.
> 
> As soon as the code is ready, the merging of the corresponding PR will close this issue and you will get a notification.
> 
> Thanks, Bruno.

Hey, @Brunoga-MS. thanks for the update!
