### ISSUE TITLE
[Question/Feedback]: Exclude some resources from being monitored

### ISSUE THREAD

**Issue by MohmadEh** [Azure/azure-monitor-baseline-alerts#127]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I have a customer requirement where several VMS are being deployed but not all VMs require Alerting. This normally is the case with Devops Runners that switch off regularly everyday at a certain period of time. Once this event happens a heartbeat alert will be fired which is not required on those VMs.
For more clarity, Consider the following example: 

there are 3 Vms, 2 Vms require the alerting but the third Vm needs to be excluded.  

I also looked into the Monitor Disable parameter in the Json however, this might have some limitation: 
1. the parameter is targeting scopes meaning all VMs will be affected and in my case i only want some VMs to have alerting disabled. 
2. In the Json itself, the Monitor Disabled isn't included within the VMs alerting

**Comment by Brunoga-MS** [comment]
Hello @MohmadEh ,
any news about this one?

**Comment by Brunoga-MS** [comment]
Hello @MohmadEh ,
given your feedback through IM, I will close this one as well, since you can apply the same solution proposed for [[Question/Feedback]: Monitor Disable Parameter #131](https://github.com/Azure/azure-monitor-baseline-alerts/issues/131).

Thanks,
Bruno.
