### ISSUE TITLE
[Feedback]:  Metric alerts for Frontdoor service should use the microsoft.cdn/profiles metric namespace

### ISSUE THREAD

**Issue by judyer28** [Azure/azure-monitor-baseline-alerts#128]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The metric alerts for frontdoor found here: https://azure.github.io/azure-monitor-baseline-alerts/services/Network/frontdoors/ should use the microsoft.cdn/profiles metric namespace not the Frontdoor classic namespace of Microsoft.Network/frontdoors.

**Comment by Brunoga-MS** [comment]
Hello @judyer28 ,
thanks for your feedback. I will make sure this will be addressed as soon as possible.

Thanks,
Bruno.

**Comment by judyer28** [comment]
Hello @Brunoga-MS, thanks for looking into this issue.  I'm actually referring to what is visible on the AMBA site here:  https://azure.github.io/azure-monitor-baseline-alerts/services/.  There is no category for CDN.  Should this issue be tagged in some way to denote that this is an issue against the AMBA site versus the GitHub repo?
@JoeyBarnes

**Comment by JoeyBarnes** [comment]
This is been fixed in #134

**Comment by judyer28** [comment]
Thanks @JoeyBarnes
