### ISSUE TITLE
[Question/Feedback]: Multiple AMBA deployments in the same tenant.

### ISSUE THREAD

**Issue by darioman1** [Azure/azure-monitor-baseline-alerts#135]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Is it possible to deploy multiple AMBA instances in the same tenant.
We have one PROD management group, containing application specific management groups and a NON-PROD management group containing application specific non-prod management groups.

Is it possible to deploy 1 AMBA instance into the PROD management group and one in the NON-PROD management group?
So two separate "alzArm.param.json" files.

Thanks

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
given the above explanation I am going to close this issue as completed. Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
