### ISSUE TITLE
[Question/Feedback]: Ability to update the Action Group displayname/shortname

### ISSUE THREAD

**Issue by carlzxc71** [Azure/azure-monitor-baseline-alerts#144]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

In the scenario where we receive alerts from several different customers & tenants we would like to be able to assign another displayname of the Action Group that is deployed with AMBA. This lets us know which tenant and customer the alert belongs to which is helpful since we have several different environments we are monitoring. 

Is there a way to modify this today? 

The way I have solved it so far is to run AZ CLI on a scheduled basis which updates the Displayname incase a new deployment has happened and a new action group has been created with the default `ActGrp` displayname we have today. 

```bash
ID=$(az monitor action-group list --query "[?name.contains(@,'AMBA')].id" --output tsv)
az monitor action-group update --ids $ID --group-short-name "<customer shortname>"
```

**Comment by Brunoga-MS** [comment]
Hello @carlzxc71 ,
thanks for your feedback. In the latest release [2024-03-01](https://github.com/Azure/azure-monitor-baseline-alerts/releases/tag/2024-03-01) we changed the action group and alert processing rules display names to include both **_AMBA_** and the subscription display name. Unfortunately it is not possible to do too much on the short name since it is limited to 12 characters, so we cannot follow the same approach.

Thanks,
Bruno.

**Comment by carlzxc71** [comment]
> Hello @carlzxc71 , thanks for your feedback. In the latest release [2024-03-01](https://github.com/Azure/azure-monitor-baseline-alerts/releases/tag/2024-03-01) we changed the action group and alert processing rules display names to include both **_AMBA_** and the subscription display name. Unfortunately it is not possible to do too much on the short name since it is limited to 12 characters, so we cannot follow the same approach.
> 
> Thanks, Bruno.

Hello & thank you for your response @Brunoga-MS 

Unfortunately having the subscription name does not solve our problem since we do not use customers names in the displayname of subscriptions and in the scenario where several customers can run similar workloads such as ARC or AVD they can possible have the same name. 

Our wish is being able to update the displayname of the actiongroup and if that is not possible today maybe we can add that to a "wishlist"? 

We can run our script in the meantime but we would rather have the ability to configure everything in the same solution ofcourse.

**Comment by Brunoga-MS** [comment]
Hello @carlzxc71 ,
I cannot assure that we will add a parameter for the customer name to be used in the APRs/AGs but I will investigate. What about adding the customer name as Tag.

Thanks,
Bruno.

**Comment by carlzxc71** [comment]
> Hello @carlzxc71 , I cannot assure that we will add a parameter for the customer name to be used in the APRs/AGs but I will investigate. What about adding the customer name as Tag.
> 
> Thanks, Bruno.

Understood. I am afraid that tags does not solve our issue as it does not appear in the email from Azure Monitor to my knowledge.

**Comment by Brunoga-MS** [comment]
> > Hello @carlzxc71 , I cannot assure that we will add a parameter for the customer name to be used in the APRs/AGs but I will investigate. What about adding the customer name as Tag.
> > Thanks, Bruno.
> 
> Understood. I am afraid that tags does not solve our issue as it does not appear in the email from Azure Monitor to my knowledge.

They do not unless you use a custom email template through Logic App where you can modify/enrich the email body

**Comment by carlzxc71** [comment]
> > > Hello @carlzxc71 , I cannot assure that we will add a parameter for the customer name to be used in the APRs/AGs but I will investigate. What about adding the customer name as Tag.
> > > Thanks, Bruno.
> > 
> > 
> > Understood. I am afraid that tags does not solve our issue as it does not appear in the email from Azure Monitor to my knowledge.
> 
> They do not unless you use a custom email template through Logic App where you can modify/enrich the email body

I will look into that, thank you.

**Comment by Brunoga-MS** [comment]
Closing this one not in our plan to implement that.
