### ISSUE TITLE
Migration to GA AMBA blocked by remediation due to conflict

### ISSUE THREAD

**Issue by stevedistef** [Azure/azure-monitor-baseline-alerts#155]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I had been running pre-GA "ALZ-monitor" in an unaligned environment (one MG and one subscription) and yesterday decided to migrate to the azure-monitor-baseline-alerts GA version.  
I saw the documentation indicating that a cleanup was required and that there was no 'migration', so I executed the cleanup scripts as guided in the docs:
1) PS /home/steve/AMBAGA/azure-monitor-baseline-alerts/patterns/alz/scripts> ./Start-ALZMonitorCleanup.ps1 -WhatIf    
2) PS /home/steve/AMBAGA/azure-monitor-baseline-alerts/patterns/alz/scripts> ./Start-ALZMonitorCleanup.ps1 -Force 
I got good output: 

> Found '0' resource groups with tag '_deployed_by_alz_monitor=True' to be deleted.
> Found '5' policy assignments with metadata '_deployed_by_alz_monitor=True' to be deleted.
> Found '7' policy set definitions with metadata '_deployed_by_alz_monitor=True' to be deleted.
> Found '134' policy definitions with metadata '_deployed_by_alz_monitor=True' to be deleted.
> Found '5' role assignment with description '_deployed_by_alz_monitor' to be deleted.
> WARNING: This script will delete the resources discovered above.
> Deleting alert resources...
Several pages of "Ture" followed by
True                                                                                                                    
Deleting role assignments...
**Cleanup complete.**

Then I forked the repository, updated the json parameters file, and ran the deployment against the same AMBA-Unaligned MG which contains the one Subscription with all my resources.   I waited until all the reminants of ALerts and Policy were gone before starting.

Then I ran the deployment which completed without errors:
PS /home/steve/AMBAGA/azure-monitor-baseline-alerts/patterns/alz> New-AzManagementGroupDeployment -Name "amba-GeneralDeployment" -ManagementGroupId $pseudoRootManagementGroup -Location $location -TemplateUri https://raw.githubusercontent.com/stevedistef/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json -TemplateParameterFile "./alzArm.param.json"

snip:  Outputs                 : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          deployment       String                     "amba-GeneralDeployment has successfully deployed."

OK, so now it is on the REMEDIATION.  It was 4PM EST for me so I ran remediation fully expecting it would require a couple hours....

I ran these one line at a time and waited for each to complete before proceeding.

$pseudoRootManagementGroup = "AMBA-Unaligned"
$identityManagementGroup = "AMBA-Unaligned"
$managementManagementGroup = "AMBA-Unaligned"
$connectivityManagementGroup = "AMBA-Unaligned"
$LZManagementGroup= "AMBA-Unaligned"
#Run the following commands to initiate remediation (one at a time).
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $managementManagementGroup -policyName Alerting-Management
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $connectivityManagementGroup -policyName Alerting-Connectivity
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $identityManagementGroup -policyName Alerting-Identity
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $LZManagementGroup -policyName Alerting-LandingZone
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Alerting-ServiceHealth
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Notification-Assets

I saw the ne Policy initiative go green and went home.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/f1b7736a-19ee-45b9-bc80-6a2f26b101b2)

This morning, I arrived and so only a small improvement:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/175642b9-8f30-45ed-b2ec-21efb4123d4b)

Looking closer at Connectivity:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/cee0aa15-c806-40ec-879f-79bf6b4739fb)

I looked inside the connectivity initiative and saw that the resources are still showing they require remediation:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/0cb80791-13f6-4539-a2fa-514474b982c1)

And look at the error message from 17 hours ago:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/8ca812d2-442d-4796-8cd1-41c1009a6a14)

Says there is a conflict with data that was there fromn 3/14 (yesterday).   Is this the older AMBA which I cleaned up???

So I am looking across all remediation teaks from yesterday afternoon:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/04950850-9f95-4d3f-8267-f545acda4298)

Notice the one from this morning at ~9AM, which was me attempting a manual remediation against just the DNS Zones....  
It now (this morning manual remediation) says completed:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/9a8dcbfe-93b9-4ba9-a22c-12c35979b301)

Yet, its still showing non complient, but look at the reason here!!!!????
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/ed4f26aa-5f20-427b-b25b-9bc765651df6)

This might require a shared desktop session withsomeone before I mess up the environment with multiple remediation retries....

**Comment by stevedistef** [comment]
I am manually remediating resources.    Its slow and painful.   But perhaps I moved too fast from Cleanup to redeploy...   
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/f237a6be-5a8f-4a68-8de3-35fc83f1126f)

**Comment by Brunoga-MS** [comment]
Hello @stevedistef,
thanks for your feedback. We will investigate on this issue.

Thanks,
Bruno.

**Comment by stevedistef** [comment]
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/2fc327db-9f50-44b3-9e1c-b5db3d242a96)
 With Bruno's recommendation, I touched all 4 of these Policy Definitions, which did not seem to exist in the PRE-GA AMBA inside the "connectivity" initiative, so this is not a regression for these "connectivity" alerts.   The recommendation was to modify the "." to a "-" on a few lines as follows:
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/e6b86b66-12b8-41a6-a779-169ce5f33aa6)

I re-ran the Connectivity remediation and am now waiting to see if the alerts get created and the policy becomes compliant for each.

**Comment by stevedistef** [comment]
The Storage Account Delete noncompliance policy definitions seems to have been reported already and there is an ICM for this, I am told.

**Comment by Brunoga-MS** [comment]
@stevedistef : Storage Account Delete alert issue has been resolved.

**Comment by Brunoga-MS** [comment]
@stevedistef , I found out that the existenceCondition contains a wrong value of 2 whilst the alert got created with 4. We tried changing the value to 4 and run the remediation and we are now waiting for confirmation.

**Comment by stevedistef** [comment]
nice work, @Brunoga-MS .  That worked in my environment (Changing those 4 policy definitions to "4".).
After deleting the existing alerts in Monitor for the resource I had in my environment, we waited for it to show non compliant.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/8df70e49-0296-4da1-b5d7-c4fda74fe668)

Then executed remediation (only for Connectivity).

PS /home/steve/AMBAGA/azure-monitor-baseline-alerts/patterns/alz/scripts> ./Start-AMBARemediation.ps1 -managementGroupName $connectivityManagementGroup -policyName Alerting-Connectivity

That Completed.
After ~ 5 minutes….

Bellisimo!
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/60bd7229-89ed-48b6-80d4-70117b5ebc93)

Grazie Mille!

**Comment by Brunoga-MS** [comment]
Hello @stevedistef 
based on your results, I am going to close this one as resolved. I will make sure to apply the suggested fix to the code ASAP.
Feel free to reopen it or to create a new one, should it be the case.

Thanks,
Bruno.

**Comment by stevedistef** [comment]
Thank you for your hard work!

**Comment by stevedistef** [comment]
Hey @Brunoga-MS I just today synched my fork with the central repository, which based on your closed comment  last month, should have been fixed (meaning the fix included).  I deployed and remediated yet those four are back as non compliant.

Are we supposed to delete the actual created alerts when we deploy the fix?

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/8973e77f-1bc3-4624-8513-a87c613279da)

**Comment by Brunoga-MS** [comment]
Hey @stevedistef,
the fixes have not been included yet. PR is there but not merged. Once merged, no need to remove existing alerts; just redeploy.

Thanks,
Bruno.

**Comment by stevedistef** [comment]
Any ETA on this?
Thanks!

**Comment by Brunoga-MS** [comment]
Hopefully end of this month, beginning of May

Thanks!
