### ISSUE TITLE
ERROR: Unable to retrieve url https://raw.githubusercontent.com/........

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/azure-monitor-baseline-alerts#156]
Hi all,

I'm getting the below error message from within my Azure pipeline.

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/c303e86f-e1a9-496c-b0d5-72e6df84c958)

ERROR: Unable to retrieve url https://raw.githubusercontent.com/thuas-itops/azure-monitor-baseline-alerts-tst/main/patterns/alz/alzArm.json

In my github repo I see the following.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/fbc56a24-9889-484d-a2e4-62471555e43a)

Any idea what is going wrong?

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
thanks for your feedback. Are you able to see the file from the <> Code menu?

<img width="954" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/26008435/a8c236e1-fcdb-4794-b148-727432e287ab">

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
strange that you see mine in your fork ... click on the Raw button and copy the URL from the browser address bar ... what does it look like?

**Comment by jerrolmossel** [comment]
https://[raw.githubusercontent.com/thuas-itops/azure-monitor-baseline-alerts-tst/main/patterns/alz/alzArm.json?token=GHSAT0AAAAAACPUDD5SIZYVDXWTCB5W5TJAZPUO3FA]

Should it be a forked repo? The documentation says so but I've cloned it to make it a private repo.

**Comment by Brunoga-MS** [comment]
it's ok, just take the first part without the token and make sure it looks formatted like this 
**_https://raw.githubusercontent.com/thuas-itops/azure-monitor-baseline-alerts-tst/main/patterns/alz/alzArm.json_**

**Comment by jerrolmossel** [comment]
Ok, but that's the same path I have in my sample-pipeline.yml

variables:
  location: "westeurope"
  ManagementGroupPrefix: "hhs"
  serviceConnectionName: "AMBA-Service-Connection"

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: "Deploy AMBA ARM template"
    inputs:
      azureSubscription: ${{ variables['serviceConnectionName'] }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg create --template-uri https://raw.githubusercontent.com/thuas-itops/azure-monitor-baseline-alerts-tst/main/patterns/alz/alzArm.json --location $(location) --management-group-id $(ManagementGroupPrefix) --parameters ./patterns/alz/alzArm.param.json

**Comment by Brunoga-MS** [comment]
did you make your repo public or managed the access correctly?

**Comment by jerrolmossel** [comment]
The repo is private. I got some windows here I had to provide access when connecting from Azure devops to my github repo

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/17069820-ff88-4966-a7f4-182b03f443eb)

**Comment by Brunoga-MS** [comment]
The best practice and the documented way is to fork. please fork it and let me know

**Comment by jerrolmossel** [comment]
@Brunoga-MS 
I changed the repo from private to public and I could run my azure pipeline succesfully so it has to be an access/authorization problem at my side.
Thank you for thinking along. Issue solved. I will follow up your advice to fork according the documentation :) .

**Comment by Brunoga-MS** [comment]
@jerrolmossel ,
glad that the issue got resolved. Based on that I am going to close it as resolved.

Thanks,
Bruno
