### ISSUE TITLE
[Feedback]: Failed to build site locally using Hugo Server 

### ISSUE THREAD

**Issue by judyer28** [Azure/azure-monitor-baseline-alerts#162]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

When trying to run hugo server with latest changes, the following error is occurring:
$ hugo server -D
Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
Error: Error building site: failed to render shortcode: "C:\Users\judyer\source\repos\amba\azure-monitor-baseline-alerts\docs\content\patterns\alz\deploy\Deploy-with-Azure-Pipelines.md:6:1": failed to render shortcode "include": failed to process shortcode: "C:\Users\judyer\source\repos\amba\azure-monitor-baseline-alerts\docs\layouts\shortcodes\include.html:2:5": execute of template failed: template: shortcodes/include.html:2:5: executing "shortcodes/include.html" at <$p.RenderShortcodes>: can't evaluate field RenderShortcodes in type page.Page
Built in 6416 ms

**Comment by judyer28** [comment]
I just made sure and still same issue.  To double check I just cloned the AMBA repo and same issue.  See here:

<img width="1200" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/60985418/ab2a144a-a12f-49a9-859d-3f9ae78332d5">

**Comment by Brunoga-MS** [comment]
I will try to reach out to you later today to compare files. In my case, with my fork aligned with Main, it is working.

**Comment by judyer28** [comment]
@Brunoga-MS let me try updating my Hugo version.  I was speaking with Joey and he is using a later version.  I'll let you know if that doesn't fix my issue.

**Comment by judyer28** [comment]
@Brunoga-MS, upgrading to latest version of Hugo (v0.124.0) worked.  Closing this issue.
