### ISSUE TITLE
Can we add a Parameter to adjust "Number of Violations" 

### ISSUE THREAD

**Issue by stevedistef** [Azure/azure-monitor-baseline-alerts#177]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We noticed that we cannot adjust options which appear as "Advanced" in the portal, using the AMBA json.
While we are extremely appreciative of the effort the AMBA team invested in picking the best practice alerts, we found some cases where we would like to still use the AMBA repo and deploy from it, but we dont have the flexibility in the template parameters file to make the adjustments we need.

This is an example.  There are probably more, but this one is the one we need to adjust now.  We get too many false positives with the value as provided.

VMHeartbeat
So in the portal we see that there is an adjustment allowed to set the # of violations from 1 - 6, with the default being 2 and AMBA hardcodes this as 2 (since there is no parameter to change it).
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/159309739/dad56364-d81f-41ab-a23b-273e2d87bc9e)

Here is the json template parameter file,  Notice there is no option (parameter) to adjust that.
        "VMHeartBeatRGAlertSeverity": {
          "value": "0"
        },
        "VMHeartBeatRGWindowSize": {
          "value": "PT15M"
        },
        "VMHeartBeatRGEvaluationFrequency": {
          "value": "PT5M"
        },
        "VMHeartBeatRGAutoMitigate": {
          "value": "true"
        },
        "VMHeartBeatRGAutoResolve": {
          "value": "true"
        },
        "VMHeartBeatRGAutoResolveTime": {
          "value": "00:10:00"
        },
        "VMHeartBeatRGPolicyEffect": {
          "value": "deployIfNotExists"
        },
        "VMHeartBeatRGAlertState": {
          "value": "true"
        },
        "VMHeartBeatRGThreshold": {
          "value": "10"
        },
        "VMHeartBeatRGOperator": {
          "value": "GreaterThan"
        },
        "VMHeartBeatRGTimeAggregation": {
          "value": "Average"
        },

Might it be possible to expose that as a parameter and include it in the next build?

**Comment by Brunoga-MS** [comment]
Hello @stevedistef ,
thanks for your feedback. The idea sounds interesting. We will investigate on this request and let you know.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @stevedistef ,
we added your request to our backlog. Given that, I will close this issue as resolved

Thanks,
Bruno.

**Comment by stevedistef** [comment]
I don't think this should be resolved until it is.  Most customers using GitHub issues do not have access to internal mS backlog resources.
Can we mark it a different way so it's still visible so others can see it is being worked on?

**Comment by Brunoga-MS** [comment]
@stevedistef , we could make it "Close as not planned" which is not the case or leave it opened and sitting for the time being. I would prefer to close it since it is now under our control.

**Comment by paulgrimley** [comment]
Lets leave it open @Brunoga-MS i have added a tag to capture the request
