### ISSUE TITLE
[Question/Feedback]: Is it possible to exclude subscriptions (remove amba from them) after remediation ?

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/azure-monitor-baseline-alerts#179]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/

I have remediated  the policy initiatives but noticed that remediation also occurs on subscriptions outside my landingzones management group (but inside the pseudroot management group). I want to turn this of for these 'out of scope' subscriptions because this is not intended.
Can I just make a exclusing scope on the inititiative Assignment policies and remove the resources which are deployed to the out of scope subscriptions or is there another way to achieve this?

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
thanks for your feedback. As part of the ALZ, we need to target every subscription which is part of the ALZ. With that said, there's a way to disable monitoring on 'unwanted' subscriptions. take a look at the [
Disabling Policies](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Disabling-Policies/) documentation page with particular focus on the [MonitorDisable parameter](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Disabling-Policies/#monitordisable-parameter) section

**Comment by jerrolmossel** [comment]
Hi Bruno, thank you for your feedback. So I should remove the AMBA deployment.
Deploy AMBA and deploy it again. Then before remediating follow the MonitorDisable parameter section?

I've read the section. can you explain further where I have to be to modify this? Which policy (or file)?

**Comment by Brunoga-MS** [comment]
Hi @jerrolmossel ,
the tag must be configured on the resource for which you would like to disable alerts ... in your case at the subscription level. No changes on the policy definitions.

Thanks,
Bruno.

**Comment by jerrolmossel** [comment]
@Brunoga-MS. The subscriptions I want to exclude are part of a 'custom' management group we had created in the ALZ structure. It's located one level below the pseudo root management group (same level as Platform, Landingzones).
What will happen if a new subscription will be created within that 'custom' management group? If I place the tagname 'MonitorDisable' with value “true” will it prevend amba from being deployed to that subscription?

**Comment by Brunoga-MS** [comment]
@jerrolmossel Yes if you create the tag immediately. The tag will basically exclude the resource from policy evaluation and hence it must be present before the manual or automatic remediation is triggered.

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
I heard no news or further comments about this one, so I am going to close it as resolved.
Feel free to reopen it or to create a new one, should it be the case.

Thanks,
Bruno.
