### ISSUE TITLE
Syntax error in the 6 policies for Service Health Alerts

### ISSUE THREAD

**Issue by ClinteRich** [Azure/azure-monitor-baseline-alerts#181]
Hi,

I picked up the six policies for resource health alerts at Services>Resources>Subscriptions. They fail to deploy with the below.

**Location:**
https://github.com/Azure/azure-monitor-baseline-alerts/tree/main/services/Resources/subscriptions

**Error:**
When you try to deploy any of the above you get the following error:

`The deployment failed with error(s). Showing 1 out of 1 error(s). Status Message: The policy
     | 'Deploy_activitylog_ResourceHealth_Unhealthy_Alert' has defined parameters 'enabled,alertResourceGroupName,alertResourceGroupTags,alertResourceGroupLocation,effect' which are not used in  
     | the policy rule. Please either remove these parameters from the definition or ensure that they are used in the policy rule. (Code:UnusedPolicyParameters)  CorrelationId:
     | 1b935cef-1cd2-4162-a022-f8c44191d7a2`

**Cause:**
It looks like all the files need a find/replace for '[[' to '[' it looks like the parameter declarations have that double opening square brace and that's what is causing error.

Incorrect Example:
`"location": "[[parameters('alertResourceGroupLocation')]",`

Corrected Example:
`"location": "[parameters('alertResourceGroupLocation')]",`

All files in the directory need a full find/replace as it occurs all over the place. Once I corrected this all templates deployed successfully.

Thanks!

**Comment by Brunoga-MS** [comment]
Hello @ClinteRich ,
thanks for your feedback. The syntax is correct it written that way to force the evaluation of the function during in the policy evaluation and not during policy deployment as documented at [Scenario: Policy supported functions processed by template](https://learn.microsoft.com/en-us/azure/governance/policy/troubleshoot/general#scenario-policy-supported-functions-processed-by-template). AMBA-ALZ policies are not meant to be deployed as standalone. There's a deployment guide using different methods (PowerShell, Az CLI, Azure Pipelines and GitHub actions) to help you out. If you only need Service Health alert follow the documentation at [Deploy only Service Health Alerts](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-only-Service-Health-Alerts/)

Hope that helps.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
@ClinteRich ,
I heard no news or further comments about this one, so I am going to close it as resolved. 
Feel free to reopen it or to create a new one, should it be the case.

Thanks,
Bruno.
