### ISSUE TITLE
error message Start-AMBACleanup.ps1

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/azure-monitor-baseline-alerts#182]
Hi, 

I'm getting the below error message after running  the AMBA cleanup script Start-AMBACleanup.ps1

Any idea what could be going wrong or where to look?

Line |
 210 |  … ch-Object { Remove-AzResource -ResourceId $_ -Force:$force -Confirm:( …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | NoRegisteredProviderFound : No registered resource provider found for location 'global' and API        
     | version '2015-01-01' for type 'actionRules'. The supported api-versions are
     | '2018-11-02-privatepreview, 2019-05-05-preview, 2021-08-08-preview, 2021-08-08, 2023-05-01-preview'.   
     | The supported locations are 'global'. CorrelationId: b25a3211-e260-486
     
208: # delete alert processing rules
209:    Write-Host "Deleting alert processing rule(s)..."
210:    $alertProcessingRuleIds | Foreach-Object { Remove-AzResource -ResourceId $_ -Force:$force -Confirm:(!$force) }

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
thanks for your feedback. Which release did you deploy? I tried in my environment the latest and the previous releases and did not get any error. The line that generates the error is using the same functions and PowerShell modules of the preceding ones.
I suspect a temporary issue, hence could you try again? Can you please also send the command you use for deployment?

Thanks,
Bruno.

**Comment by jerrolmossel** [comment]
@Brunoga-MS It's a forked repo from a couple of weeks ago. I can't find which release it is. Where to look for it?

I got the error message several times in a row in a period of an hour. I started deleting the alert processing rules manually and after the last one got deleted the error message didn't occur anymore and the cleanup script continued and finished with no errors.

**Comment by Brunoga-MS** [comment]
@jerrolmossel it looks like your alert processing rules got corrupted or were created with some old API/code (which is difficult to figure out why). What AMBA-ALZ release did you deploy? Could you please do a clean deploy and try again?

**Comment by jerrolmossel** [comment]
@Brunoga-MS My forked repo is https://github.com/thuas-itops/azure-monitor-baseline-alerts-prd.
I will run a clean deploy

**Comment by Brunoga-MS** [comment]
@jerrolmossel : Repository looks good enough. Seems to be in sync with the last content. Let me know about how it goes with a clean deploy.

**Comment by jerrolmossel** [comment]
I ran a clean deploy and afterwards the cleanup script. Works fine now.
The only difference with before is that I also ran the remdiation script.

For now I can proceed and run a clean deploy again. Thank you :)

**Comment by Brunoga-MS** [comment]
Perfect. Run a clean deployment, run the remediation and try the cleanup script again.

**Comment by jerrolmossel** [comment]
@Brunoga-MS I have gone through the steps you mentioned (clean deployment, run remediation and run the cleanup script again) but getting the same error message again 

Deleting role assignments...
Deleting alert processing rule(s)...
Remove-AzResource: C:\Data\Azure\AMBA\azure-monitor-baseline-alerts-prd\patterns\alz\scripts\Start-AMBACleanup.ps1:210:48
Line |
 210 |  … ch-Object { Remove-AzResource -ResourceId $_ -Force:$force -Confirm:( …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | NoRegisteredProviderFound : No registered resource provider found for location 'global' and API        
     | version '2015-01-01' for type 'actionRules'. The supported api-versions are
     | '2018-11-02-privatepreview, 2019-05-05-preview, 2021-08-08-preview, 2021-08-08, 2023-05-01-preview'.   
     | The supported locations are 'global'. CorrelationId: 2f55d94c-b81b-466a-950f-8cd2a30b4218
PS C:\Data\Azure\AMBA\azure-monitor-baseline-alerts-prd\patterns\alz\scripts>nt/managementGroups/hhs/providers/Microsoft.Authorization/policyDefinitions/Deploy_VM_dataDiskReadLatency_Alert".

**Comment by jerrolmossel** [comment]
These are the alert processing rules which are not being deleted by the script. Is this expected behaviour?
 
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/51243261/f7db63fb-03be-4100-9d9d-046ac37dba15)

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel ,
this is not the expected behavior but a consequence of the error you got above. Unfortunately I am not able to repro your issue. It looks like something too specific. Can you check and make sure the provider **_Microsoft.AlertsManagement_** is correctly registered in all subscriptions?

**Comment by jerrolmossel** [comment]
@Brunoga-MS : Yes, I double checked this and all subs have Microsoft.AlertsManagement correctly registered.

We have 3 tenants. The only difference with the other 2 tenants (where I don't have issues with the cleanup script) is the inclusion of a seperate management group (MG) within the ALZ deployment hierarchie. That means we have a MG direct under the pseudo root MG (at the same level of platform MG).    

Once again I removed the alert processing rules manually and deployed AMBA again. Deployment inc remediation goes fine. Do you think I'm good to good with this deployment? I have no errors after deployment and getting alerts in my mailbox.

**Comment by jerrolmossel** [comment]
@Brunoga-MS Thank you 💯

**Comment by jerrolmossel** [comment]
@Brunoga-MS Thank you 💯
