### ISSUE TITLE
[Question/Feedback]: Use a single centralized action group?

### ISSUE THREAD

**Issue by markroloff** [Azure/azure-monitor-baseline-alerts#184]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Seeing as it's possible to use a single action group across multiple subscriptions' alerts, would it be possible to build this deployment to take advantage of that? I work with a lot of SMBs that tend to have smaller LZ deployments and smaller internal teams, so there's not always appetite for the same action group repeated over a dozen subscriptions. I can manually modify the policies to use a single centralized action group but the build process handling this could be nice.

**Comment by Brunoga-MS** [comment]
Hello @markroloff ,
thanks for your feedback. We do have plans for this scenario in the near future. However, we are very close to release a version that will allow customers to use their own action groups and alert processing rules. This feature could be an interesting workaround for your request.

Hope that helps.

Thanks,
Bruno.

**Comment by markroloff** [comment]
I'll keep my eyes open for it! Thanks @Brunoga-MS !

**Comment by Brunoga-MS** [comment]
Hello @markroloff  ,
based on that, we will add this into our backlog and I am going to close this issue as resolved. Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
