### ISSUE TITLE
[Question/Feedback]: Syntax defaultValue vs defaultvalue

### ISSUE THREAD

**Issue by steph409** [Azure/azure-monitor-baseline-alerts#185]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi,

I am currently writing the terraform implementation for the amba. When I deploy the policies per script and them manage via terraform, I saw that there is a configuration drift for 12 policies. Examplary, I put one example here, where you can see in pink the changes default***v***alue vs default***V***alue and allowed***V***alues vs allowed***v***alues.

When you look at the [definition file](https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/services/Compute/virtualMachines/Deploy-VM-DataDiskSpace-Alert.json) and search for e.g. defaultvalue, you can see that it is inconsistent in the json-files. Is there are reason for it? 

<img width="788" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/33083326/e8a20997-a82f-4654-999b-09d26ea870e2">

**Comment by Brunoga-MS** [comment]
Hello @steph409 ,
thanks for your feedback. There's no reason for this difference. It's more about the syntax checker some time not enforced. They do behave exactly the same so you can ignore this difference in JSON. Is it creating any problem in Terraform?

Thanks,
Bruno.

**Comment by steph409** [comment]
Hi Bruno,
thanks for the quick reply. For terraform, it is annoying because terraform tries to update the resources each time it runs (inconclusively). If you don't mind, I will prepare a pull request with the changes, to make the configuration consistent. I just don't wanted to go through the work, and then learn that there is a reason for the differences.
BR, Stephanie

**Comment by Brunoga-MS** [comment]
@steph409 fine to me and thanks in advance :-)

**Comment by Brunoga-MS** [comment]
@steph409 : perfectly fine and thanks.
