### ISSUE TITLE
[Question/Feedback]: New Alert - No Action Group

### ISSUE THREAD

**Issue by ChrisTIEVA** [Azure/azure-monitor-baseline-alerts#190]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello, 
I have deployed AMBA and everything seems to be configured correctly, but when I initiated the remediation tasks it didn't automatically create the new alerts with an action group associated with it. Also, when i create a new resource to test e.g. a VNet, it creates the new alert fine, but again no action group associated with it.

**Comment by ChrisTIEVA** [comment]
Im getting the following:

The ApiVersion '2024-03-01-preview' is not registered for ResourceType 'Microsoft.AlertsManagement/actionRules'. Valid Api Versions are:  '2018-11-02-privatepreview' '2019-05-05-preview' '2021-08-08-preview' '2021-08-08' '2023-05-01-preview'.\

**Comment by ChrisTIEVA** [comment]
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/148763475/c331b1a0-ccc0-4390-a70d-d294febe2453)

**Comment by simone-bennett** [comment]
I'm also getting this and am unable to manually remediate the two failed policies.

**Comment by Brunoga-MS** [comment]
Hello @ChrisTIEVA ,
thanks for you feedback. We are actively investigating this issue that was never experienced before. 

Thanks,
Bruno.

**Comment by simone-bennett** [comment]
Awesome thanks. I'm deploying this for a customer atm if I can collect any logs or screenshots to help let me know.

**Comment by Brunoga-MS** [comment]
Hello @ChrisTIEVA ,
it looks like the issue was caused by a problem with the Microsoft.AlertsManagement/actionRules resource provider. It should be fixed now. Please try again and let us know.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @ChrisTIEVA ,
in regards to the alerts and action groups, the only ones with action groups are those for Service Health. All the other alerts we create do not have any action group associated since we rely on the Alert Processing Rule (which should be su correctly created now).

Hope that helps.

Thanks,
Bruno.

**Comment by ChrisTIEVA** [comment]
Yes thankyou - I assumed that was the case in the end and manually created an APR.

Since deployed to a new tenant and all is working fine. 

Cheers,

Chris
