### ISSUE TITLE
[Question/Feedback]:  AGW Alert Deploy Failed for "Deploy AGW BackendLastByteResponseTime" and “Deploy AGW ApplicationGatewayTotalTime”  

### ISSUE THREAD

**Issue by grazianosommariva** [Azure/azure-monitor-baseline-alerts#194]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Both AGW Alerts Deploy fails with message:
2BadRequest","message":"Time aggregation must be one of [Average, Maximum]

**Comment by Brunoga-MS** [comment]
Hello @grazianosommariva ,
thanks for your feedback. We will investigate the issue and apply the necessary fix as soon as possible.

Thanks,
Bruno.
