### ISSUE TITLE
[Question/Feedback]:  Notification assets naming

### ISSUE THREAD

**Issue by alexeyzolotukhin** [Azure/azure-monitor-baseline-alerts#207]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello. 

The new naming pattern for notification assets seems to be :
- [concat('ag-AMBA-', subscription().displayName, '-001')]
- [concat('ag-AMBA-SH-', subscription().displayName, '-001')]
- [concat('apr-AMBA-',subscription().displayName, '-001')]

Is this something we can assume to be used in the future? What is the "001" suffix for? Right now it is hard coded... Is it simply to ensure uniqueness of the asset name at the time of the first deployment or will it be auto-incremented in the future based on some condition(s)?

The reason I am asking is because I am thinking of creating a bicep that re-deploys these groups and adds email recipients to them based on which subscription the group is located in. My expectation is that I will end up with the same action groups containing only the recipients that are relevant for each particular landing zone. I believe this should work, but I must be sure that the action groups I deploy and the action groups AMBA deploys match, hence this question 😊|.

Thank you!

**Comment by Brunoga-MS** [comment]
Hello @alexeyzolotukhin ,
thanks for your feedback. The reason why we started using that naming convention is to align with the [Abbreviation recommendations for Azure resources](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) and the '-001' at the end is to make sure we can create additional resources with similar name maintaining, as you well spotted, the uniqueness of the asset name. For instance, we now have a suppression alert processing rule which has a similar name but ends with '-002'.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @alexeyzolotukhin ,
I haven't heard anything back from you regarding this issue. Assuming that it can be considered resolved, I am gonna close it as completed. Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
