### ISSUE TITLE
[Question/Feedback]: Non Resource/Service Health Alert Rules don't have action group assigned

### ISSUE THREAD

**Issue by anorwood-xten** [Azure/azure-monitor-baseline-alerts#210]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'm deploying the AMBA templates via Powershell and am running into a strange issue; none of the Metrics, Activity Log or Log Search alert rules have an Action Group assigned to them.

The Service Health and Resource Health alerts do though.

This is a brownfield site, and I don't have any failed remediation tasks related to the Notification policy, which is showing as 100% compliant:

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/80894796/d73bf12f-dffd-485b-8560-cce1b466400f)

Is there something specific I can check as to why these alerts have no action group associated with them?

**Comment by Brunoga-MS** [comment]
Hello @anorwood-xten ,
thanks for your feedback. What you reported here is not an issue but it is the normal behavior. We do not assign action group to Metrics, Activity Log or Log Search alert rules; instead we do use the Alert Processing Rule (APR). Service Health alerts cannot use APRs so we had to assign an action group to them.

Hope that clarifies.

Thanks,
Bruno.

**Comment by anorwood-xten** [comment]
Hi Bruno,

That clears it up completely, thank you for that! I'll skulk back into my hole now.

Cheers,

Anthony

**Comment by Brunoga-MS** [comment]
Thanks to you Anthony,
based on that I am going to close this one as completed. 

Fell free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
