### ISSUE TITLE
[Feature Request]: Add alert for data limited reached for Log Analytics workspaces

### ISSUE THREAD

**Issue by SteveBurkettNZ** [Azure/azure-monitor-baseline-alerts#213]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Can we possibly get an alert added for when we reach the **set daily cap limit** on a Log Analytics workspace, and it stops accepting additional logs please?

Thanks!

**Comment by paulgrimley** [comment]
Hi @SteveBurkettNZ this has recently been raised to us and is on our backlog, no timescales as of yet though as we have some pressing priorities to attend to.
