### ISSUE TITLE
[Question/Feedback]: AVD Pattern Storage Account Calculation in Automation Account is wrong.

### ISSUE THREAD

**Issue by christianGoe** [Azure/azure-monitor-baseline-alerts#221]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

It Seems that the AvdStorageLogData Runbook calculates the $RemainingPercent = 100 - ($shareUsageInGB / $shareQuota) wrong.

it should be $RemainingPercent = 100 - ($shareUsageInGB / $shareQuota * 100)

**Comment by JoeyBarnes** [comment]
Hi @christianGoe - I have assigned this to @JCoreMS to comment on this since he is the pattern owner.

**Comment by JCoreMS** [comment]
DOH! Great catch and find and not sure how I missed that and the fact this is 3weeks old.  I will work on this in an update for fixes here shortly.  Thanks @christianGoe for the feedback.
