### ISSUE TITLE
[Question/Feedback]: InvalidDeployment error 'location' not specified in patterns\alz\templates\userAssignedManagedIdentity.json

### ISSUE THREAD

**Issue by francovanzyl96** [Azure/azure-monitor-baseline-alerts#230]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

 When attempting a default deployment of the AMBA I am getting the below error in my deployment pipeline.
 
 {"code": "InvalidDeployment", "message": "The 'location' property must be specified for 'amba-id-amba-prod-001'. Please see https://aka.ms/arm-deployment-subscription for usage details."}
 
 From a quick look the issue seems to be in the template file: patterns\alz\templates\userAssignedManagedIdentity.json
 
 The location parameter is not being specified in the "Microsoft.Resources/deployments" resource

**Comment by Brunoga-MS** [comment]
Hello @francovanzyl96 ,
thanks for your feedback. Could you please check if you put the value for the management subscription in the parameter file?

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/26008435/b8a8e9d2-4414-4307-b4dc-077defe0b569)


Thanks,
Bruno.

**Comment by francovanzyl96** [comment]
Adding the managementSubscriptionId resolved the issue, thanks.
