### ISSUE TITLE
[Question/Feedback]: Deploying definitions for non-pattern services.

### ISSUE THREAD

**Issue by Leeg14** [Azure/azure-monitor-baseline-alerts#233]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Well done everyone involved, this is great work! 

We have deployed the ALZ pattern and it is working well, however we would like to generate definitions for other services using the  recommended values on the AMBA site which have not been included in the ALZ pattern. 

Is this something I could do myself using the generate-templates.py and point it at (for example) the sql\managedinstances\alerts.yaml and generate ARM templates for the managedinstance alerts in the yaml file, or am I misunderstanding what the purpose of the generate-templates.py is? I suppose I'd like to be able to get to a point where I can roll my own 'pattern' file like policies.json and have a tidy monitoring deployment for bespoke services, not just ALZ. Is this possible?

**Comment by JoeyBarnes** [comment]
Hi @Leeg14  - 

The generate-templates.py tool was developed to create ARM and Bicep templates (and Terraform in the near future) for all alerts in the repo for use in the AMBA website.   That being said, you can use it locally to create those templates for your own usage.  It is also a good example of how to programmatically walk thru all the alerts in your repo and "do somthing" based on the data in the alerts.

**Comment by EG-EG** [comment]
This is relevant to what we are trying to do. We would like to in effect roll our own 'pattern' containing database alerting but can't see a way of doing this. Is database alerting on the roadmap to be created in the alz, or is there some additional tooling used to create the policies.json file in patterns\alz\policydefinitions folder that would allow us to do ourselves without writing from scratch? Thanks :)

**Comment by arjenhuitema** [comment]
Hi @EG-EG, thank you for your feedback. The ALZ pattern currently doesnt have database alerting on the roadmap. 

The policies.json is generated with [patterns\alz\templates\policies.bicep](https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/patterns/alz/templates/policies.bicep). It does require the policies to be created before they can be loaded into the policies.json.

If you would like to create additional "policy.json" files for custom deployments you need to update the following variables in policy.bicep to include your PolicyDefinitions and PolicySetDefinitions:

```
var loadPolicyDefinitions = {
}
```

```
var loadPolicySetDefinitions = {
}
```

When policies.bicep has been updated you can build the json file with `bicep build` like:

`bicep build .\patterns\alz\templates\policies.bicep --outfile .\patterns\alz\policyDefinitions\policies.json   `

**Comment by EG-EG** [comment]
Thanks, I'll have a look into this :)
