### ISSUE TITLE
[Bug]: Deploy_ERP_ExpressRoutRxLightLevell_Alert Has a Typo 

### ISSUE THREAD

**Issue by bzabber** [Azure/azure-monitor-baseline-alerts#237]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The Deploy_ERP_ExpressRoutRxLightLevell_Alert has a typo in the name, it should be Deploy_ERP_ExpressRoutRxLightLevel_Alert, without two lowercase Ls in "Levell".

**Comment by Brunoga-MS** [comment]
Hello @bzabber ,
thanks for your feedback. Based on our internal conversation, I will assign it to you for the necessary fix.

Thanks,
Bruno.
