### ISSUE TITLE
Long running operation failed with status 'Failed'. Additional Info:'The 'location' property must be specified for 'amba-id-amba-prod-001'

### ISSUE THREAD

**Issue by Pawel1985** [Azure/azure-monitor-baseline-alerts#240]
Hello

when I try to deploy AMBA using Azure CLI or Azure PowerShell and I use default parameter:
    "bringYourOwnUserAssignedManagedIdentity": {
      "value": "No"
    },

then I receive following error when I try what-if deployment
New-AzManagementGroupDeployment :
InvalidDeployment - Long running operation failed with status 'Failed'. Additional Info:'The 'location' property must be specified for 'amba-id-amba-prod-001'. Please see https://aka.ms/arm-deployment-subscription for usage details.'

when I look into the template, there is a template error only affecting me when bringYourOwnUserAssignedManagedIdentity equals 'No'

Template validation failed: The template resource 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[System.String]' at line '29' and column '9' is invalid. 'ResourceGroup' property is not allowed for for the current template deployment. Please see https://aka.ms/arm-template/#resources for usage details.arm-template (validation)
userAssignedManagedIdentity.json(29, 9): The error occurred in a linked template near here

all works when I use bringYourOwnUserAssignedManagedIdentity equals 'Yes' and I add resource ID of my UAMI using bringYourOwnUserAssignedManagedIdentityResourceId parameter

**Comment by Brunoga-MS** [comment]
Hello @Pawel1985  ,
thanks for your feedback. This issue has been already reported in [#GH ISSUE 230](https://github.com/Azure/azure-monitor-baseline-alerts/issues/230). A User Assigned Managed Identity is now required and you have the option to either use your existing one or to create a new one during the deployment. Should you use your own, make sure it has the Monitoring Reader role assigned at the pseudoRoot management group. Documentation is in the process of being updated. 

If you set the parameter to No, make sure check if you put the subscription id of the management subscription in the parameter file.

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/26008435/a332abe8-7825-4d13-9663-50880def541a)

Thanks,
Bruno.

**Comment by Pawel1985** [comment]
thanks a lot @Brunoga-MS
