### ISSUE TITLE
[Question/Feedback]: Monitoring ARC enabled servers

### ISSUE THREAD

**Issue by darioman1** [Azure/azure-monitor-baseline-alerts#245]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi
Is it possible to monitor ARC enabled servers with AMBA?
BR
Dario

**Comment by Brunoga-MS** [comment]
Hello @darioman1 ,
thanks for your feedback. It is definitely possible to monitor Hybrid (or Arc) VMs. This was added in the last release (we are updating the documentation in these days). Looking at the code you will see a new policy initiative called **_Deploy Azure Monitor Baseline Alerts for Hybrid VMs_**

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/26008435/eab2316b-04ea-49ef-811f-0c382c25ddec)

containing hybrid vm alerts

<img width="185" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/26008435/ab251e9b-b84d-4af3-a942-502b3f66c3a5">

Thanks
Bruno.
