### ISSUE TITLE
[Question/Feedback]: Fillter the parts disk with tags id 

### ISSUE THREAD

**Issue by flexo44** [Azure/azure-monitor-baseline-alerts#248]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hey team.

I'm providing some context: I need to monitor partitions on Ubuntu VMs, but the boot and snap partitions are showing up in my monitoring and triggering false alerts.

Do you know if there's a way to filter these partitions so they don't show up in Grafana?

Thanks for your feedback.

**Comment by Brunoga-MS** [comment]
Hello @flexo44 ,
thanks for your feedback. As far as I know, it should be possible to further filtering what is displayed in Grafana. Adding @judyer28 and @JoeyBarnes for further comment on the Grafana side.

Thank,
Bruno.

**Comment by judyer28** [comment]
Hello @flexo44,
Are you using a Logs query in your panel?  If so, the following is a quick example of filtering out the boot and snap partitions using the InsightsMetrics table:

```
InsightsMetrics
| where Origin =~ 'vm.azm.ms' and Namespace =~ 'LogicalDisk' and Tags has 'vm.azm.ms/mountId'
| extend partition=tostring(todynamic(Tags)["vm.azm.ms/mountId"])
| where partition !has '/boot' and partition !has '/snap'

```

**Comment by flexo44** [comment]
Hello, 
I tried to modify the query, but I don’t know the path to follow after installing the JSON API plugin. 
You can see it in the screenshot below, the field to modify the query is not editable. 

<img width="595" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/58995062/639bb548-2441-4947-8bf2-f403484b4fbf">

Thank you in advance

**Comment by judyer28** [comment]
Hello @flexo44, that particular query is using a "Dashboard" data source, which means it is getting its query from another panel on the dashboard.  You want to edit the Disks panel here:
<img width="298" alt="image" src="https://github.com/Azure/azure-monitor-baseline-alerts/assets/60985418/03c373aa-b4ae-44a0-bd70-2c261dc96cc7">

I am also attaching a user guide that was put together for this dashboard that should help. 
[Azure Infra Monitoring Dashboard.docx](https://github.com/user-attachments/files/15928024/Azure.Infra.Monitoring.Dashboard.docx)

Let me know if I can help with any further questions.
Regards,
Justin

**Comment by flexo44** [comment]
I have added the filter in the disk panel and it works. Thank you for the documentation.

Have a good day.
