### ISSUE TITLE
[Question/Feedback]: Deploying AMBA

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-monitor-baseline-alerts#253]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Command example in https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-with-Azure-CLI/#4-deploying-amba is wrong.

```powershell
az deployment mg create --name "amba-GeneralDeployment" --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/2024-03-01/patterns/alz/alzArm.json --location $location --management-group-id $pseudoRootManagementGroup --parameters ".\patterns\alz\alzArm.param.json"
```

should be

```powershell
az deployment mg create --name "amba-GeneralDeployment" --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json --location $location --management-group-id $pseudoRootManagementGroup --parameters ".\patterns\alz\alzArm.param.json"
```

ie. it references an older version of the alzArm.json file.

**Comment by arjenhuitema** [comment]
Hi @spaelling, 

Thank you for your feedback. Yes, this version should be updated. We will review the latest release of AMBA and make the necessary updates to the documentation. We are deliberately pointing to a release version and not to main as this gives us more control when there are updates to AMBA. 

Thanks again for your feedback and I will let you know when the changes have been made.

Arjen
