### ISSUE TITLE
Feedback: No treshold parameter for ALZ alerts

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-monitor-baseline-alerts#260]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The ALZ alerts 

- `ALZ_WSFMemoryPercentage` 
- `ALZ_WSFCPUPercentage`
- and others

has no treshold parameter. This seems like a huge oversight. I would really like to avoid having to maintain anything but the `alzArm.param.json` file.

**Comment by Brunoga-MS** [comment]
Hello @spaelling ,
thanks for you feedback. We will investigate and get back to you.

Thanks,
Bruno.
