### ISSUE TITLE
[Question/Feedback]: displayname VMLowOSDisk(Write/Read)LatencyAlert should be  VMHighOSDisk(Write/Read)LatencyAlert

### ISSUE THREAD

**Issue by Sergiovdh** [Azure/azure-monitor-baseline-alerts#261]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

In the https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/policyDefinitions/policies.json we see the displayname -VMLowOSDiskwriteLatencyAlert which is triggered by a greater than value the correct displayname should be -VMHighOSDiskwriteLatencyAlert
Same goes for the -VMLowOSDiskReadLatencyAlert it should also have the VMHighOSDiskReadLatencyAlert displayname in my opinion.

**Comment by Brunoga-MS** [comment]
Hello @Sergiovdh ,
Thanks for you feedback. We will work on this as soon as possible.

Thanks,
Bruno.
