### ISSUE TITLE
Specify a different name for each ALZ Monitor Resource Group?

### ISSUE THREAD

**Issue by Greg-Court** [Azure/azure-monitor-baseline-alerts#277]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Currently in the alzArm.param.json file, we are able to provide a value for `"ALZMonitorResourceGroupName"`.
This sets the name of all ALZ Monitor resource groups, meaning that each RG has the same name across all subscriptions.

Is it possible to provide a different name for each subscription or each management group at least?

**Comment by Brunoga-MS** [comment]
Hello @Greg-Court ,
thanks for your feedback. We will look at your request and let you know.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
@arjenhuitema could you please comment

**Comment by arjenhuitema** [comment]
Hi @Greg-Court,

Thank you for your input. We have considered it and while the adaptability of this proposal is interesting, it's not possible for us to adopt it. 

Implementing a different resource group name for each subscription or management group would necessitate the programmatic inclusion of the subscription or management group name, or ID, into the name of the resource group. Although technically possible, it may not be favored by all users.

Each organization has different naming standards, abbreviations and practices, it is impossible for us to align with all standards, this is why we usually use and default to CAF [naming conventions](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming) and [abbreviations ](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) for resources.

I am going to close this issue now. Thank you again for your feedback, and if there are any more questions, please feel free to ask.
