### ISSUE TITLE
[Question/Feedback]: How can I easily identify all specific severity level alerts and disable them?

### ISSUE THREAD

**Issue by Greg-Court** [Azure/azure-monitor-baseline-alerts#287]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi,
As in the title, I am looking for the easiest way to identify and disable all level 4 severity alerts without having to go through the alzArm.param.json and disable them one by one. Example of some of the verbose alerts I would like to disable:

![image](https://github.com/user-attachments/assets/4ef2358b-6bf0-4244-8457-6cfef35c0edd)

Potentially I would be looking at disabling level 3 as well.

Is there an easy way to do this, or do I need to manually go through, find them all, disable them all?

CTRL + F "4" in the alzArm.param.json only returns 5 hits (PDNSZQueryVolumeAlertSeverity, PIPPacketsInDDoSAlertSeverity, PIPBytesInDDoSAlertSeverity, PIPPacketsInDDoSAlertSeverity, PIPBytesInDDoSAlertSeverity) - was hoping this would return more, allowing me to easily identify all L4 alerts

Am I missing something?

Thank you in advance.

**Comment by Greg-Court** [comment]
Hi @Brunoga-MS,

Thanks for getting back to me. Is there somewhere where I can look up this information to find out the severity level of each alert based on the variables in the alzArm.param.json file? I am happy to manually go through each alert and disable the verbose or informational ones but is it possible to deduce the associated severity level without deploying / triggering them?

Thanks,
Greg

**Comment by Brunoga-MS** [comment]
Hi @Greg-Court ,
all the severity params ends with **_Severity"_**, so you can simply search for that string. 

<img width="206" alt="image" src="https://github.com/user-attachments/assets/a116d2ca-41c6-4712-bf7f-cf41f2cd58b9">


Adjust the value considering the following mapping table:
<img width="104" alt="image" src="https://github.com/user-attachments/assets/d1ef44a0-4a63-4f3b-8ea1-f743bac54082">

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @Greg-Court ,
is there any further help needed on this one? if not, can it be closed?

Thanks,
Bruno.
