### ISSUE TITLE
[Question/Feedback]: Handling multiple subscriptions in AVD pattern runbook

### ISSUE THREAD

**Issue by abkgaard** [Azure/azure-monitor-baseline-alerts#289]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

For the runbooks that are supposed to collect data from host pools and storage accounts, the context is not changed when querying through storage accounts. Also I find that the default subscription may be different, than the one that they reside in.

For the hostpool runbook, since it takes subscriptionId as a parameter, we could set the context to that subscription ID.
```powershell
[CmdletBinding(SupportsShouldProcess)]
param(
	[Parameter(Mandatory)]
	[string]$CloudEnvironment,
    [Parameter(Mandatory)]
    [string]$SubscriptionId
)

Connect-AzAccount -Identity -Environment $CloudEnvironment | Out-Null

#### Add this line
Set-AzContext -SubscriptionId $SubscriptionId

$AVDHostPools = Get-AzWvdHostPool -SubscriptionId $SubscriptionId
```
For the storage account runbook, I suggest to handle it in the foreach - if our context is incorrect, correct it and then walk through the commands:
```powershell
# Foreach storage account
Foreach ($storageAcct in $storageAccountResourceIDs) {


    ##### Context handling - add this block
    $Subscription = (Get-azSubscription -SubscriptionId ($StorageAccountResourceIDs -split '/')[2])
    $SubName = $Subscription.Name
    
    #Get current context
    $Context = Get-AzContext
    if ($Context.Subscription.Id -ne $Subscription.Id) {
        Set-AzContext -SubscriptionId $Subscription.Id
        Write-Output "Changed context to subscription $($Subscription.Name) $($Subscription.Id)"
    } 

    ##### Context handling

    $resourceGroup = ($storageAcct -split '/')[4]
    $storageAcctName = ($storageAcct -split '/')[8]
    #Write-Host "Working on Storage:" $storageAcctName "in" $resourceGroup
```

**Comment by JCoreMS** [comment]
Thanks for the input and feedback @abkgaard .  Version 2.0.0 just released and incorporates the add for the Storage Runbook as well as an option to select in the UI Definition during deployment to select storage in alternate subscriptions.
