### ISSUE TITLE
[Question/Feedback]: Alert naming parameters rather than static

### ISSUE THREAD

**Issue by relent0r** [Azure/azure-monitor-baseline-alerts#291]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Issue : The default naming conventions for the alert names (specifically service health) are static in the ARM deployent section so cannot be modified to suit client naming standards.

e.g
"name": "ServiceHealthIncident",

We are looking to update these to have optional parameters for these and was wondering if there is any desire to have this available at the source. 
I'm unsure if there is a reason why they are currently static, perhaps preventing character limit issues or issues around mg/sub naming?

Is there any appetite for this?

**Comment by Brunoga-MS** [comment]
Hello @relent0r ,
thanks for your feedback. The idea sounds interesting, and we will evaluate it. Just consider that there's a limit of 20 params per policyDefinition and a total of 400 per policySetDefinitions. Some policyDefinition are already up to that limit of 20 params and some policySetDefinition are close to 400 params. With that said, you will probably not be able to parametrize all of them.

I would also ask @arjenhuitema opinion here.

Thanks,
Bruno.

**Comment by arjenhuitema** [comment]
Hello @relent0r,

Thank you for reaching out to ensure that the changes you're implementing will have a positive impact at the origin. While we value the recommendation, we currently will not make further updates to the service/resource health policies as they are transitioning to Azure Built-in policies.

I’m curious to learn what changes you are making to see if that’s applicable to other policies.

Thanks,
Arjen

**Comment by Brunoga-MS** [comment]
hello @relent0r ,
is there anything you can share about changes you're making that could be passed to the team during the service/resource health policies transition to Azure Built-in policies?

Thanks,
Bruno.

**Comment by relent0r** [comment]
Hi @Brunoga-MS , the initial feedback you gave on the parameter limitations made enough sense that I could see the issues I would create by making the changes I was thinking of. Happy to close this issue.
