### ISSUE TITLE
Getting this error (The provided information does not map to a role assignment.) when trying to run the start-ambacleanup.ps1 script

### ISSUE THREAD

**Issue by lmjaanes-mck** [Azure/azure-monitor-baseline-alerts#302]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We deployed to the Connectivity and Management Management Groups and I remediated the policies in the Connectivity Management Group. I have run this cleanup script before multiple times and have never gotten this issue.
<img width="657" alt="amba_issue" src="https://github.com/user-attachments/assets/5a53a061-9a8a-4e7e-b04e-e24de19af899">

**Comment by arjenhuitema** [comment]
Hi @lmjaanes-mck, thank you for your feedback. Since it usually works, is there anything different in your current deployment? Could you provide the command you used to deploy AMBA, so I can check the version? I'll review the script and try to replicate the issue.

**Comment by arjenhuitema** [comment]
Hi @lmjaanes-mck, I've reviewed the script and I havent been able to replicate the issue. 

However, due to a separate issue, the script has been updated. Could you try running it again with the newest version?

**Comment by arjenhuitema** [comment]
Thank you for your feedback. I'll close the issue since we couldn't replicate it. Please inform us if it happens again.
