### ISSUE TITLE
[Question]: Arc Servers not monitored

### ISSUE THREAD

**Issue by PvErning** [Azure/azure-monitor-baseline-alerts#309]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello,
The Alerts like high CPU are not monitored because the scope is "All virtual machines".
When I create a copy of the alert rule and change the scope to "All machines - Azure Arc" then it works.

Is the scope by design only "All virtual machines" or can we activate also the Azure Arc machines?

**Comment by PvErning** [comment]
With rolling out like the solution descripted in [Question/Feedback]: Deploying AMBA #253. HybridCompute is enrolled and the monitoring of Arc servers works great! THX.

**Comment by arjenhuitema** [comment]
Thank you for your feedback. The documentation regarding the issue you mentioned will be updated next week. I'm pleased that you found the solution. I will now close this issue, but if you have any additional feedback, please let us know.
