### ISSUE TITLE
[Question/Feedback]: How to enable AVD Pattern for multiple Host Pools and different Actions Groups?

### ISSUE THREAD

**Issue by andura0991** [Azure/azure-monitor-baseline-alerts#315]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I am trying to enable AVD Pattern on a new host group and with a new Action Group, during deployment this error is displayed:

Account already exists in another resource group in a subscription. Resource Group Name: "rg-name" (Code: Bad Request)

<img width="342" alt="image" src="https://github.com/user-attachments/assets/fc38ec41-7a09-4631-8889-ec2af5440033">

<img width="388" alt="image" src="https://github.com/user-attachments/assets/ca8a2a81-5027-4ac3-bd41-b6d628ed9412">

**Comment by JCoreMS** [comment]
Great find!  Perhaps what we can do is append a random GUID or characters to ensure uniqueness in the Action Group name.  This will be added to the backlog and hopefully fixed in the very near future.
