### ISSUE TITLE
[Question/Feedback]: AMBA alerts usability in an environment with a single additional Management Group

### ISSUE THREAD

**Issue by maheshau1** [Azure/azure-monitor-baseline-alerts#320]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I am currently working in an environment where we have multiple subscriptions organized under the root management group. Additionally, there is only one other management group created specifically for a business unit, as depicted in the attached diagram.

Given this structure, is it still possible to effectively utilise AMBA for alerting across these subscriptions and an additional MG? If so, are there any specific configurations or considerations we need to be aware of?

<img width="780" alt="image" src="https://github.com/user-attachments/assets/38ff1f71-1446-4e88-9d5e-caeb81d50282">

**Comment by Brunoga-MS** [comment]
Hello @maheshau1 ,
thanks for your feedback. While this is not a technical requirement we really discourage to deploy directly to the Tenant Root Group as documented at [Can I deploy to Tenant Root Group?](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/FAQ/#can-i-deploy-to-tenant-root-group).

Hope that helps.

Thanks,
Bruno.
