### ISSUE TITLE
[Question/Feedback]: "The existing policy parameter(s) 'MonitorDisable' were not found in the policy being updated"

### ISSUE THREAD

**Issue by IEP-Brewin** [Azure/azure-monitor-baseline-alerts#328]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi,

I'm trying to deploy AMBA version 2024-09-02 (from version 2024-06-05), but getting the following error:
**"The existing policy parameter(s) 'MonitorDisable' were not found in the policy being updated. The parameter names can not be changed"**

I've ended up deleting all of the AMBA policy assignments/remediations and also the deployments to the ALZ management group, but still getting the error.

**Comment by Brunoga-MS** [comment]
Hello @IEP-Brewin ,
thanks for your feedback. The issue you encountered seems to be something related to a different parameter file content. To resolve the issue make sure the parameter file structure you are using is aligned with the one coming with the release you would like to deploy. For any reference, the update procedure is documented at [Update to new releases](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/UpdateToNewReleases/) and when a pre or post action is required you can find it documented in the specific section. In this case, you can find this info in the [Updating from release 2024-06-05
](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/UpdateToNewReleases/Update_from_release_2024-06-05/) page.

Hope that helps.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
@IEP-Brewin can you pls share a copy of your param file. Share it privately pls.

**Comment by IEP-Brewin** [comment]
How would i share privately? Thanks.

**Comment by Brunoga-MS** [comment]
Please give the steps in the below list a try:

1. Get the correct parameter file from the [2024-09-02](https://github.com/Azure/azure-monitor-baseline-alerts/tree/2024-09-02/patterns/alz) code version
2. Populate the parameter file with your info/settings
3. Clean existing installation using the cleanup procedure documented at [Cleaning up a Deployment](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Cleaning-up-a-Deployment/)
4. Populate the necessary variables and deploy the release **_2024-09-02_** using this command: **_New-AzManagementGroupDeployment -Name "amba-GeneralDeployment" -ManagementGroupId $pseudoRootManagementGroup -Location $location -TemplateUri "https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/2024-09-02/patterns/alz/alzArm.json" -TemplateParameterFile ".\patterns\alz\alzArm.param.json"_** or any other available method of your choice between Azure CLI, Azure Pipelines, GitHub Actions, Azure Portal Accelerator

**Comment by Brunoga-MS** [comment]
Can you please go through each of the management group under the pseudo root one 

![image](https://github.com/user-attachments/assets/5a1a88be-b21f-4209-bfdb-4630f1df9b9f)


and manually remove the assignment

<img width="740" alt="image" src="https://github.com/user-attachments/assets/f0809934-72f1-4707-a296-845ac2b096d3">

After everything is perfectly clean, try the deployment once again.

Thanks,
Bruno.

**Comment by IEP-Brewin** [comment]
If i search for `AMBA` in IAM on each of the 3 management groups, there are no results - Therefore i can't manually delete the role assignments.

**Comment by IEP-Brewin** [comment]
I've managed to do a full cleanup (see attached image), but still getting the same error.
![image](https://github.com/user-attachments/assets/1ae9e61c-a7cd-4abe-92eb-3e3818bc7d98)

**Comment by Brunoga-MS** [comment]
Hi @IEP-Brewin ,
this sounds like impossible to believe. With a clean environment like you made it after the cleanup there's no policy to update.

Is there any direct contact of yours that you can share?, I would love to have quick Teams meeting to go through it together and see why it is not working.

thanks,
Bruno.

**Comment by IEP-Brewin** [comment]
Please reach out to Jay Withers - ***@***.******@***.***>.

Many thanks.

***@***.***

**Comment by Brunoga-MS** [comment]
As expected the email address got obfuscated ...

**Comment by IEP-Brewin** [comment]
How about jay.withers brewin.co.uk (just add the @ in the middle)

**Comment by jaywithersbrewin** [comment]
This is my individual work account. I've temporarily added my email to my bio

**Comment by Brunoga-MS** [comment]
Reaching out to you in Teams

**Comment by Brunoga-MS** [comment]
@IEP-Brewin ,
during our meeting we found that there was an old deployment. After the clean-up you were able to successfully deploy the new version.

Based on that I am going to close this issue as resolved. Feel free to re-open it or create a new one if need be.

Thanks,
Bruno.
