### ISSUE TITLE
Request feature to setup static treshold

### ISSUE THREAD

**Issue by ChrisPolewiak** [Azure/azure-monitor-baseline-alerts#332]
https://github.com/Azure/azure-monitor-baseline-alerts/blob/b367149b2b09d78054155fc52a15b72d4c8b8b37/services/Cdn/profiles/Deploy-CDNP-Percentage4XX-Alert.json#L184

**Comment by Brunoga-MS** [comment]
Hello @ChrisPolewiak ,
thanks for your feedback. Could you please expand a bit more on the problem and the change you would like to propose?

Thanks,
Bruno.

**Comment by ChrisPolewiak** [comment]
Of course

We have a customer who requires to setup a static threshold for the alerts for Front Door Errors.
I know the we can change this dynamic threshold to low or high - but they expect to setup static value in %.

So, we have an option to edit alert rules manually - which generate a risk that after AMBA update Alert will be overwritten
Or to create new alert rules, which will be in conflict with current policy, and its disable this nice automation feature 🙂





Best Regards



Krzysztof "Chris" Polewiak
Azure & Security MVP

Cloud Solutions Architect

Microsoft Certified Trainer



e-mail


***@***.******@***.***>


 [cid:75c69415-b8a4-4514-a698-5ab36fa7b5ef]


LinkedIn


https://bit.ly/polewiak


GitHub


https://github.com/chrispolewiak


MVP Profile


https://bit.ly/polewiak-mvp






Best Regards



Krzysztof "Chris" Polewiak
Azure MVP

Cloud Solutions Architect

Microsoft Certified Trainer



e-mail


***@***.***>***@***.******@***.***>


 [data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHwAAAA2CAYAAAAF3f20AAAAAXNSR0IArs4c6QAAIABJREFUeF7tnAd4FWXa938zp6Y3SAIBEgghkB5CQAQEBKVaAREEpKlgb7vqWteyYqEjiNgoisuCIkiTjvTeWwIJkIQUUk/KqTPf9cycALZdWHWv93vfHS9Rkjkzz/P87/q/7/tIPL1N5b/X/5kTkP4L+P8ZrLWN/sGAyyCpSKqKqqogych4UCTxahn+a1v+49L2xwEuCTQFqEbwuEF1AEYwmMDgAlXS//3v9R89gT8OcFQkZFSXhyhLLUNvackPJy+y85QTfHyRVLd2x3+v/+wJ/L6AS5Kw4ICiQak4nIRZnbx3bxKj2kWx82IFj3x2kP35gMWMpCn5L9h17Ue/jzBceYr+Hk3IxA+9r5VQ9Hepsr7m+g9o6/LeePUSr17v77jOX4NdW4E4KLFgbY2q9o920P/G+/8AwMXiJFSng4bWGt6+J4VRmVGa7wYD+wqreOTTA+zKU8HHgiR5fu7KNVP/2wGXVAlJEvHD1d5DAC5OSqxHCKiKKmILRQfcI+vgIwlBEPfVH6wXEu3nV13i3j/wksRZygoGRcWjWDRl0hZqcHjdouG63v67Aq5LnwlcLsItNbx7TxL3ZzYG3HiQMGgHaGTPRRsPz9/P3lw3+Pohq+4rmqWp4e8AuKbICqqGmzgkAaL3cDSF8Xjx9EqDsE4GCdXjAacLjCYwGbxruUrF/8OAX5Z7twJOByaDhEfImFHsxei1pdeO+e8EuH4gmjQ6FMIstUwelsrw9IjLmqQbeRGxgyTJ7Cys4In5R9id40ayWlFloXHe63cBXLzLg0ly4yO5tLc7VRO1ihFkCyhuTJITX4MHVVVwqBacHgi1emjfMozckjpOXnShGs3ePVyLhtf7iXqT4rVSV7mQqzZ5jVbMAB4Vf6Odu9IC6R4TTK5DZvr3OZTbrSB5QFglzex7XaEwafWu6yf287cDLjQDD7IKHkcdDXycTBrWjuGpAuwrmZdQtHrjJyyBWNDuwkoenX+APbluJIuf7kMNTlCFZv1WUykhu2t4tnc0A5IbaO/ecLaEl5fk4DQEIqs1PNijKfelR2gp44ZcO+8u2suj/drw8q0t2XahhpEf7aKw2opkkJE0KyFWbsCggCK7UGSv/9eyEQWjots4Rcs469NOYVkkZFW4LhVVHJSkIruFCzFoGipMtvi87D0XRbNG4tniRUYkZw3juzVm0oAEhFHfVa1wxzsbKSqSCAi1oCgSdS497VUUFwbxTI+CeCJmE8husWCvOPxGpk0LvMSD7U4i/Gt5d3AiI9KbXga73hj+zEhrebnEnhIbj87dx+4cwOqDJLl0mfytgIvHu6r4bHQq96c30taTVVHH7VP3c7LYTYifk/kP30C/mADtd8vO2BgxZR3PDe7AC50bs6/czYBp2zhXbtAArw/5hDAaVAGq4v2ZNyZQZU3oVdmNKlJRTcTcXk1TkVVFz0S1+KA+OvQKtQBEC8K88YO2d0WPbxQZX6pYPD6DPq3CWbg3n/fW53KhqoZhHZrSpXUk767IZld2DRZZpXljE6nNAlCcKrvzqjlXroBs1t3abydeVD3SdnoIt9YyaUi6pjH1gY5y2czoe/xxGFYfBcO+khoenbefndkOJN8AJNzX7Zt+5sVUCYO7ipnDE3kwswmKqlCjygz5+BAr9pbQppGBJY92pE1DYbJllp4qY8Ts3QRZfOkeZyCnUmVnngu3LEyqBA7XFa0zWvXduOw6tyAbQXGC2Ud3XM66q2ybDCYzsmzUImyP+IwqBEGPurFYdG7Co4LLAYpLlxWPEcy+2nv8PXmse/ZG2kdHcs+srSzeVEJsGx82vdyDSIOJm6ds4ofD1cTGBNM/PZhWkRY8LiPbc8pYeaSaKrvgP/TTv36T7k0RRHSrmTiHnUgfD+/el8bw1IbejUi6sF6Fwk8BF/ohDkASpkaGvUVVPPHlIbafVpCsFiRZmEChFcI0/hsRuwDcY2PW8ERGtWvMpcoqGgQF8dQ3J5ixMoeb4wNY9HgnXLXlRAaHsOxUJcNmbad540Z0jfUht9LF9ycqcbg8BJod9EqOJKFpIFUuhRW7CzEqcEtGOKWVdoqKy0lMaMrKfWWcO3+JPhmNSGruj6waOJxTzuqjhdjVEAweB7HhKr1SGhMRYqSyDr7ec54zZWKtdjq3CODGxAgsJjh50c6KAwW4PAaGZQTxZv9WNAz0Z/7Oc+zKdxAdLPFAl2b4m4zM23mB+bsvUoeb5IYKbZo2oqLKxomiGrblGiiqcoJBCLZwv9dt0sWHhHkwaGA39XMwaXg6A5PCNXivTlqu3Qvr2n6wuIYn5x9g8xm7FsgJ2VKEL9NM5HVeqoTRY+PD4UkMa9eYfaeyaduqBV9sO8dDn+1nXO94JgxK4sTZ86S3iOK70zaGTF3P+NsymNQ7ho35dm6fugO3s443BsTzeJdYxJHVAI/94zB1ZdXMe+hGqpwubNWVRIc2YMTnOwkPsvLa7WkEeBMCm1vl5RUnmLo6hxbhgcwZncLN0UEI3lGI8ch5e1m45TxDbormnUEpNPUxaRsVNmD61rN8uOYoC5/uTdsQMx5VxXCV1dQSS9WJLJlZcKSUF+ZvZXCPeCyKHYNs5kRJFasO11HjNl7OUK4bcOHNBBGgOtxE+nuYPCSJe1OEZnuDhKtwuVbAVS0nFhpv5GhpHePm7mfbmTqw+mHEjVuzcder5RJGt40PhyUyMjOKOWu3clunthRUKNz55ve8OrIdA9s1Y+P+LG7LaMHKrGqGTF3Hw/3SmNg3lo3nbfSdvJU7Uhsxd2QaiuJh5rqTHC91sb/QTusglfmjb0AY6oOFdpYeOkdZRTl/uS2dBr4WJn5/jABZ4aGeSVxyQI93N5PcNIiFI9PJqqjitUWHkK3+HC5yUFhUyrfP3MQNjQL4YncOx/Iu8UzfVPxMZsbN244RF2/c3Y6GgX78Y/cZdl6wER1qYnSnVvgbDczflc1XByvYcLSM+KZ+NAkXTKbM8YvVnC9zgcF4WWn+DcCFu3LS2N/J+0NSGZJSH43rgF8Ny7UCroc/WryqgX6ktJZH5+1ly2knstW3PsC8ThUXPtzG7GGJjM6M4oV/bOSuzqnENAhm/IebeObOZKxWX9bvOcWzfdNZfrqKIdPWM65vKpP6xrImt4ph07bwzn0dGZ0RxrKsQoZO20GN3V/Lz4d1DGX+8DTKnS7u+XAf6/ac4+m7WzDxrkx2XCin1/ubCLbIrH6+Bwmh/oxZsA+3ovD5iEzOVtoYNWcHPxyxgTWAO26MYtH9iZTaXdz61lqOXqjh70924Z60SGYfKOTZad+x9pXbadc8nAEfbGTZ1ks0jzOz5U+30sDXh5vfW8eObAeGkDA8DpFNCFJGAYOIDzQ66ToBlxVkRSdNFLuDpgFuJg9ry4CkUK8Rl4W31eC6Pt7nx1mpDrru7Q9esvHUgsNsOlULPv4YVAOqJFIhb7DzL+G/AviYzCjGfLaJbikxDMqI4e+7z3JrUmPWnyzhh6M5zB5xE8uyKrlXAN7HC3iOjfEfbWbqyI7cFh/Gu1ty+Ms/TuExBoOzjuEdApg3oh3Hy6vp/s4PFFcaee+eaJ7t3oovd+cwct5RAnxMfPtkRzpHBfHiytN8s/ssCx/rRmqYlXPVTqZtzGHmilOM6tOGmXfEcbSwlv7T93CuzM2UIa154qYolueW8PCktSx69hbaN2vI8M/2sHBnNUnNjax+9AZC/Yz0m7mLjSeEG7Ro8Y6IfepjJt3FXgmQr0HDRSQu4DRpqVeTQA8zRqRwR+uwqzy2nlnr5ZLf7zpRVs1jCw6w/oRLA12SnajXTMr8GPBBMzfTJMyXyYMzya9yEOhn4q/fHKbQVs2CUZ359rQAfB3j+6QxqV8sa3JsPDRnC9NGdeT2uFDe33yG5xZloRgDwO1kePtg5t2fztFyG93f3solm5EJA5rwXM82LNp7niGfHyfQT2LlEzfQsXEQL6zNYcLiI7RtEcjztyVwZ0K4Fu88PG8PPhYLMwancKLEwS3TtpBf6mTmfc]


LinkedIn


<https://bit.ly/polewiak>https://bit.ly/polewiak


GitHub


<https://github.com/chrispolewiak>https://github.com/chrispolewiak


MVP Profile


<https://bit.ly/polewiak-mvp>https://bit.ly/polewiak-mvp




________________________________

**Comment by Brunoga-MS** [comment]
Hello @ChrisPolewiak ,
you are correct, AMBA updates and more important remediation will overwrite the alert rule if it not compliant anymore due to manual changes of criteria which are part of the policy existenceCondition. I can only suggest to duplicate the alert and to change the configuration on the duplicate to be a static threshold.

Hope that helps,
Bruno.

**Comment by ChrisPolewiak** [comment]
thanks for your help
