### ISSUE TITLE
[Question/Feedback]: Deployment template validation fails when selecting Yes to Bring Your Own User Assigned Managed Identity

### ISSUE THREAD

**Issue by john-joyner** [Azure/azure-monitor-baseline-alerts#336]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Using the "Deploy to Azure" button in the blog article https://techcommunity.microsoft.com/t5/azure-governance-and-management/enhancements-to-azure-monitor-baseline-alerts-for-azure-landing/ba-p/4231710.

Validation of the deployment fails when electing to use a Custom User Assigned Managed Identity (UAMI). See attached screenshots:
1. When not selected a Custom UAMI, the Management Subscription Id field is present.
2. When selecting a Custom UAMI, the Management Subscription Id field is removed.
3. The template validation fails due to missing 'managementSubscriptionId'

![AMBA-Deployment-WithoutCustomUAMI](https://github.com/user-attachments/assets/d0fc4141-61f4-4930-a8a5-d9a6314ef0a9)
![AMBA-Deployment-WithCustomUAMI](https://github.com/user-attachments/assets/830f352b-1936-448c-a651-95df99951e35)
![AMBA-Deployment-WithCustomUAMI-Failure](https://github.com/user-attachments/assets/3cf56714-0f03-49f9-9eb4-7ee4558a24f0)

**Comment by arjenhuitema** [comment]
Hi @john-joyner, we appreciate you bringing this to our attention. We will look into the issue and respond accordingly.

@tagolovina could you please review this?
