### ISSUE TITLE
[Bug]: Wrong variables for Enable Common Alert Schema in Policy Definition `Deploy_ServiceHealth_ActionGroups` and `Deploy_Suppression_AlertProcessing_Rule`

### ISSUE THREAD

**Issue by haflidif** [Azure/azure-monitor-baseline-alerts#345]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hey.

For this Configuration in Notification Assets on Policy Definition: `Deploy_ServiceHealth_ActionGroups` and `Deploy_Suppression_AlertProcessing_Rule`

![image](https://github.com/user-attachments/assets/43ae0991-f9dc-4401-8bb0-d86710eb7aef)

There is a wrong parameter/variable name on three deployment types within 
[services/AlertsManagement/actionRules/Deploy-AlertProcessingRule-Deploy.json](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/AlertsManagement/actionRules/Deploy-AlertProcessingRule-Deploy.json)
- LogicAppRecievers - [L238:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/AlertsManagement/actionRules/Deploy-AlertProcessingRule-Deploy.json#L238) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`
- EmailRecievers - [L258:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/AlertsManagement/actionRules/Deploy-AlertProcessingRule-Deploy.json#L258) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`
- ARMRoleRecievers - [L268:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/AlertsManagement/actionRules/Deploy-AlertProcessingRule-Deploy.json#L268) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`

 and [services/Resources/subscriptions/Deploy-ServiceHealth-ActionGroups.json](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/Resources/subscriptions/Deploy-ServiceHealth-ActionGroups.json)
- LogicAppRecievers - [L241:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/Resources/subscriptions/Deploy-ServiceHealth-ActionGroups.json#L241) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`
- EmailRecievers - [L261:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/Resources/subscriptions/Deploy-ServiceHealth-ActionGroups.json#L261) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`
- ARMRoleRecievers - [L271:](https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/Resources/subscriptions/Deploy-ServiceHealth-ActionGroups.json#L271) `"useCommonSchema": true` should be `"useCommonAlertSchema": true`

Will open up a PR shortly to these two PolicyDefintions to fix this.

**Comment by Brunoga-MS** [comment]
Hello @haflidif ,
thanks for your feedback. We are aware of this bug and have already captured in our backlog. We are working to get it solved soon and will keep you posted on the progress.

Thanks,
Bruno.

**Comment by haflidif** [comment]
> Hello @haflidif , thanks for your feedback. We are aware of this bug and have already captured in our backlog. We are working to get it solved soon and will keep you posted on the progress.
> 
> Thanks, Bruno.

Thanks @Brunoga-MS, sounds good, otherwise I have a open PR that fixes this, but you maybe want to have it within some kind of release maybe ?

**Comment by Brunoga-MS** [comment]
Having it as part of the next release is exactly the idea and the path that normally follow. However, we will release the fix most probably before the release so you can just deploy the main version over the current release version to benefit from the fix.
