### ISSUE TITLE
Storage free size trigger on 10GB

### ISSUE THREAD

**Issue by ChrisPolewiak** [Azure/azure-monitor-baseline-alerts#350]
https://github.com/Azure/azure-monitor-baseline-alerts/blob/2566ee16836a0d50bbabe2b06bf887ab2727c14d/services/DBforPostgreSQL/flexibleServers/alerts.yaml#L170

What is the reason to setup the default trigger for 10GB free space on PostgreSQL.
Is this related to some recommendations from database vendors?
I try to found the source of this requirements.

Thanks in advance.

**Comment by arjenhuitema** [comment]
@ChrisPolewiak, thank you for your feedback. 

@JoeyBarnes, could you take a look?

**Comment by JoeyBarnes** [comment]
Hi @ChrisPolewiak - Alerts in AMBA have 3 ways that alert details are defined.  One (verified) is through a product group verified path, which is the ultimate path.  Second (popular) is thru statistically significant data analysis based on how alerts are being deployed today. Lastly (manual), is through subject matter experts defining what the details should be.  In this case, the alerts for PostgreSQL were pulled in through the popular route.

**Comment by ChrisPolewiak** [comment]
Thanks for your comment.
