### ISSUE TITLE
[Question/Feedback]: ALZ AMBA Remediation failed

### ISSUE THREAD

**Issue by jarradpiper** [Azure/azure-monitor-baseline-alerts#353]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I've performed an update to AMBA release 2024-09-02 in my ALZ Bicep Accelerator environment including running the recommended policy clean-up script beforehand. For previous updates I would run Start-AMBARemediation.ps1 to fix any non-compliant resources or when importing brownfield subscriptions. In the Update documentation it also suggests to perform this and links to this documentation. https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/

I've tried running the script but receive the following error on all remediation tasks.
<img width="845" alt="image" src="https://github.com/user-attachments/assets/62a8fd15-f034-49dd-bac3-3b74c5bfd857">

I've noticed these policy names do not exist in the ALZ so I tried using the initiative names in ALZ i.e. ALZ_SvcHlthAdvisory. This fails with the same error.

Have I missed something, is this no longer how brownfields remediation is supposed to work in ALZ?

**Comment by Brunoga-MS** [comment]
Hello @jarradpiper ,
thanks for your feedback. The procedure you just described looks correct. I tested the remediation command again and it worked. I suspect something failed during the deployment od AMBA-ALZ. Could you please ensure that everything was deployed correctly with no failures and check the parameters file format? Make also sure you completed what is described in the [Updating to release 2024-09-02](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/UpdateToNewReleases/Update_to_release_2024-09-02/) page.

Thanks,
Bruno.

**Comment by jarradpiper** [comment]
The deployment was successful, however the remediation Script failed due to having multiple Project tags in the configuration using different cases.
