### ISSUE TITLE
When try to deploy AVD monitoring alert getting below error

### ISSUE THREAD

**Issue by tamilbabuece** [Azure/azure-monitor-baseline-alerts#365]
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '[format('c_DsktpRead_{0}', split(parameters('AVDResourceGroupId'), '/')[6])]' at line '5707' and column '5' is not valid: The language expression property array index '6' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'."}

**Comment by rchauvetclara** [comment]
same error here

**Comment by tamilbabuece** [comment]
Still we are facing same error
