### ISSUE TITLE
Support a parameter for conditions that determine when the Alert Processing Rule should trigger

### ISSUE THREAD

**Issue by JamesDLD** [Azure/azure-monitor-baseline-alerts#366]
Support a parameter for conditions that determine when the Alert Processing Rule should trigger.

**Comment by Brunoga-MS** [comment]
Hello @JamesDLD ,
thanks for your feedback. Could you please expand with some more context example? This sounds interesting.

Thanks,
Bruno.

**Comment by JamesDLD** [comment]
Hi @Brunoga-MS , I am preparing a pull request for this, it will permit end users to apply conditional filters when alert will be triggered.
This will look like this 
![image](https://github.com/user-attachments/assets/84f184d0-3745-4fc5-a69c-ef1831f939cf)

**Comment by Brunoga-MS** [comment]
@JamesDLD : the changes in the policy definition look good enough. However, we need to pass the severities as parameters so the param file and the policySetDefinition need to be changed as well.

**Comment by Brunoga-MS** [comment]
Hello @JamesDLD ,
thanks to your feedback and prototype we are implementing the filtering you suggested in a slightly different way which allows customer to create more than one if the param file is changed and the solution redeployed (and re-remediated). The previous deployed one will be maintained.

Given that, I am going to close the PR without merging it.

**Comment by Brunoga-MS** [comment]
I will close the issue once the other PR is merged.
