### ISSUE TITLE
Start-AMBARemediation.ps1 fails in Azure Government Environment

### ISSUE THREAD

**Issue by sdolgin** [Azure/azure-monitor-baseline-alerts#371]
The script [Start-AMBARemediation.ps1](https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/patterns/alz/scripts/Start-AMBARemediation.ps1) fails in the Azure Government environment with the following error message:
```
The given key 'AzureAttestationServiceEndpointSuffix' was not present in the dictionary.
```

My guess is that the base URI for ARM is [different](https://learn.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure) in Gov and not properly set when the script runs. 

- Azure Public: management.azure.com
- Azure Government: management.usgovcloudapi.net

![Image](https://github.com/user-attachments/assets/37749484-246f-49a5-8b3e-1699a0287ca2)

**Comment by Brunoga-MS** [comment]
Hello @sdolgin ,
thanks for your feedback. AMBA-ALZ is not officially supported on AzureGov environment and you are rights the the URI is different. However if you were able to deploy it, I would would give the remediation script a try using a private version containing a possible fix/workaround. Let me know if this is ok to you.

Thanks,
Bruno

**Comment by Brunoga-MS** [comment]
Hello @sdolgin ,
given the confirmation received via email, I am going to close this issue as resolved.

Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
