### ISSUE TITLE
[Question/Feedback]: Deploy LA Workspace Daily Cap Limit Reached Alert remediation fails

### ISSUE THREAD

**Issue by laingsc** [Azure/azure-monitor-baseline-alerts#372]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

ALZ_LAWorkspaceDailyCapLimitReached is the only policy that fails to remediate.  When attempting to remediation a standard LZ Management Subscription with a default LZ LA Workspace, I get the following error (RAW):
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "'where' operator: Failed to resolve scalar expression named 'disable'. A semantic error occurred.. The request had some invalid properties Activity ID: 8fd507bc-dbb8-4b12-8a5f-339b862b9ea8."
    }
  ]
}
```

This policy shouldn't fail if there's no Daily cap set, or it should show as compliant if there's no cap to alert on.

After setting a 10 gb/d limit I still get the exact same error.

**Comment by Brunoga-MS** [comment]
Hello @laingsc ,
thanks for your feedback. I started investigating the code and couldn't find any expression named '**_disable_**'. Moreover, in my test environments I have no daily cap set and the remediation does not fail. In the alert, we are not looking at the daily cap setting, but at the records you would get from the **_Operation_** table if a daily cap is set (whatever value it is set to) and the ingestion rate goes **_OverQuota_**. I suspect something with the tag name. Could you please share an image with sensitive data obscured where I can see the tagging you applied to the workspace?

Thanks,
Bruno.

**Comment by laingsc** [comment]
@Brunoga-MS thanks heaps and apologies for the late reply, I knew I was forgetting something last week.

The workspace has a custom name and custom tags, have uploaded a screenshot....

![Image](https://github.com/user-attachments/assets/551da898-0310-49f3-994d-999d0cf3790c)

**Comment by Brunoga-MS** [comment]
Hello @laingsc,
nothing in the screenshots rings a bell. are you remediating manually or through the remediation script?

**Comment by laingsc** [comment]
Manually/via my own script.  I first noticed that it failed on it's own accord however.

**Comment by laingsc** [comment]
@Brunoga-MS  omg, I forgot the most important thing and probably answered my own question:

I've got this defined in the paramaters:

    "ALZMonitorDisableTagName": {
      "value": "monitor-disable"
    },

**Comment by laingsc** [comment]
@Brunoga-MS have modified the assignment by changing the ALZMonitorDisableTagName from 'monitor-disable' to 'MonitorDisable', and remediation worked fine manually.  However our tagging convention doesn't match that so would be a minor bug.

**Comment by Brunoga-MS** [comment]
@laingsc given your feedback, can I close this issue as resolved or is there any suggestion /enhancement that you would recommend?

Thanks,
Bruno.

**Comment by laingsc** [comment]
@Brunoga-MS sorry just seen this comment now.  My suggestion would be allowing tags that contain dashes.

**Comment by Brunoga-MS** [comment]
@laingsc , thanks to your last comment I am going to reopen this one since I found the bug responsible for tags containing dashes not working.
