### ISSUE TITLE
[Question/Feedback]: Is it possible to exclude a subscription for AMBA?

### ISSUE THREAD

**Issue by AndreyYurashevich** [Azure/azure-monitor-baseline-alerts#391]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

I have an ALZ setup with some application landing zones. I want to apply AMBA to my setup but I need to exclude some of the application landing zones from AMBA. I need them in the Landing Zones management group so other policies may still apply to them.

I checked #179 but MonitorDisable tag placed on the subscription level didn't work for me as it prevented only subscription-level alerts from creating whereas plenty of resource-specific alerts were still created.

Are there any suggested solutions for such case?

**Comment by Brunoga-MS** [comment]
Hello @AndreyYurashevich ,
thanks for your feedback. Currently the only supported way to exclude an entire subscription or management group under the Landing Zones one form being alerted or targeted by policies you can create a policy assignment exemption targeted at the level you prefer (management group, subscription or resource group.

![Image](https://github.com/user-attachments/assets/61e6c7b5-9812-4f63-8cf5-767ad6d2186b)

You can even decide if you prefer to exclude the entire policy initiative (default setting proposed by the wizard) or single policy definitions

![Image](https://github.com/user-attachments/assets/326d8582-1c6b-4e5c-9cdf-bf204ba7ecc7)

Hope that helps.
Thanks,
Bruno.

**Comment by AndreyYurashevich** [comment]
So am I right that when I create a new subscription that I need exemptions for I need to look for all policy assignments that has correct metadata and create exemptions for all of them? Is there any chance that policies will trigger sooner and they will create subscription-scoped resources by the time exemptions will be created?

**Comment by Brunoga-MS** [comment]
@AndreyYurashevich you are perfectly right. Consider that when you deploy amba, the compliance check will take some time to run, hence alert creation could not be that immediate for a new subscription or resource as well. What I can recommend, of course, is to create the necessary exemptions for the given scope (maybe a management group scope is better in this case ... it scales more) before creating new subscriptions. If only need to exclude subscriptions, make sure you configure the exemptions right after.

**Comment by AndreyYurashevich** [comment]
Got it, thank you for your answers!
