### ISSUE TITLE
Question/feature request: Why is the VM initiative only deployed to Landing Zones?

### ISSUE THREAD

**Issue by MarcoJanse** [Azure/azure-monitor-baseline-alerts#399]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Why is the VM initiative only deployed to Landing Zones? I can understand that most Virtual machines will reside in Landing Zones, but how about Domain Controllers running on virtual machines that reside in the Identity management group or other VMs running in ? 

I have multiple Azure customers that use virtual machines outside the Landing Zones management group, like:

- Domain Controller virtual machines in the Identity or Platform management group.
- A network virtual appliance (NVA) in the Connectivity or Platform management group.
- A jump host/management server in the Management or Platform management group.

It would be great if this could also be deployed to additional management groups by a boolean parameter or something alike. You could even give customers the option to monitor VMs in the Sandbox if they want to.

**Comment by arjenhuitema** [comment]
Hi @MarcoJanse 

Thanks for your feedback. Good point. 

The Landing Zone initiative was recently divided into multiple initiatives to support a more modular approach. One of the reasons for this change is to facilitate precisely what you are proposing. 

We are making progress towards assigning the VM initiative to the Identity and Connectivity management groups. This work item is in our backlog and is scheduled for completion in November.

Thanks,

Arjen
