### ISSUE TITLE
[General workload issue]: #ALZ #Policy #Pattern

### ISSUE THREAD

**Issue by vivsri** [Azure/azure-monitor-baseline-alerts#405]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Other

### Description

The code for ALZ deployment pattern runs fine when we use the option of **bringYourownUserAssignedManagedIdentity** to **Yes**.
When cloned the repo locally it gives the following error for the properties under UAMI section as below.

Template validation failed: The template resource 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[System.String]' at line '29' and column '5' is invalid. 'ResourceGroup' property is not allowed for for the current template deployment. Please see https://aka.ms/arm-template/#resources for usage details.arm-template (validation)

![Image](https://github.com/user-attachments/assets/e4002f43-a3ae-42ef-944f-683b1a757e9b)

Pls let us know if this can be fixed.

**Comment by arjenhuitema** [comment]
Hi @vivsri, Thanks for your feedback. 

@Brunoga-MS Could you review this?

**Comment by Brunoga-MS** [comment]
Hello @vivsri ,
could you please ensure that the **_bringYourOwnUserAssignedManagedIdentity_** is set to **_Yes_** and you entered the UAMI resourceId? in the cloned param file? Should it be set to **_No_**, either provide the management subscription id or switch it back to _**Yes**_ and enter the UAMI resource Id.

Thanks,
Bruno.

**Comment by vivsri** [comment]
Hey @Brunoga-MS ,
It works all fine when the **bringYourOwnUserAssignedManagedIdentity** is set to **Yes**, as stated in the issue.
It doesn't seem to work when set to No, even after providing the subscription ID for the Management Subscription.
It complains for the nested resource & the properties as provided in the screenshot.

**Comment by Brunoga-MS** [comment]
We had this issue when deploying from AMBA portal accelerator or from ALZ portal accelerator but it was fixed around mid September. I tried to repro your scenario, but it worked for me. Could you please sync the forked repo once again?

**Comment by vivsri** [comment]
We tried it running directly from the source repo url, providing our own param file locally, when supplied with the UAMI ID it works, but when set to know, it gives errors like ERROR: {"code": "MultipleErrorsOccurred", "message": "Multiple error occurred: . Please see details."}.
So i guess if i use the source repo directly, I'm using the latest code.

**Comment by Brunoga-MS** [comment]
Are you deploying the MAIN or the release 2024-09-02 code?

Main has the fix, release 2024-09-02 it does not. The fix has been incorporated into the latest release which is 2024-11-01

**Comment by vivsri** [comment]
I'm using the MAIN >> --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json

**Comment by Brunoga-MS** [comment]
Perfect. I just went through the deployment using MAIN as well and it worked fine.

![Image](https://github.com/user-attachments/assets/0034f054-7600-4ce8-a356-f877b2d81893)

At this point, I think we should investigate on the parameter file. Could you please check for any relevant difference between your param file and the screenshot of the one I just used?

![Image](https://github.com/user-attachments/assets/117edbec-e5e6-4fec-b1b0-37dae36576e5)

**Comment by vivsri** [comment]
Great, so it just worked for me too using the URL with the tag now >> --template-uri  https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/2024-11-01/patterns/alz/alzArm.json \

Just to be sure the tag is for Nov 1st 2024, right.

The param file is identical, shall i give it a try using the main now.

**Comment by vivsri** [comment]
hey @Brunoga-MS,
Thanks for your time, my last run using the MAIN now works.

**Comment by Brunoga-MS** [comment]
Great new @vivsri .

I am very happy that we got it solved. Based on your feedback I am going to close this one as resolved. Fell free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.
