### ISSUE TITLE
[General workload issue]: "Deploy Hybrid VM Disconnected Alert" remediation issues

### ISSUE THREAD

**Issue by agiegg** [Azure/azure-monitor-baseline-alerts#411]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Question

### Description

Has anyone else had any issues remediating the above policy? I have deployed the hybrid vm initiative and all of the other policies are remediating ok  however this one does not. With the other policies if I remediate a single resource then this makes the policy compliant for all resources, however if I try this for the 'Deploy Hybrid VM Disconnected Alert' the then remediation task says '0 out of 0' resources remediated and the policy stays in a non-compliant state. Remediating the full subscription causes a lot of errors (suspect its due to duplicate deployment names). Has anyone successfully remediated this policy?

**Comment by Brunoga-MS** [comment]
Hello @agiegg ,
thanks for your feedback. We are not aware of any issue with that policy or its remediation task at the moment. There was one fixed 2 month ago and the fix it now part of both Main and 2024-11-01 release. Could you please make sure you are using one of the latest version I mentioned and that you have Arc machines in the Landing Zone subscriptions?

Thanks,
Bruno.

**Comment by agiegg** [comment]
Hi @Brunoga-MS. We do have Arc machines in our subscriptions, lots of them!

We are using the 09-2024 release at the moment. I can see that there has been some work done via this: -

https://github.com/Azure/azure-monitor-baseline-alerts/pull/323

Would you expect that to address the issue? We will update anyway, however just trying to understand if you believe it should address the issue before we do. Many thanks :)

**Comment by Brunoga-MS** [comment]
Hi @agiegg ,
yes the issue is expected to be fixed in the 2024-11-01.

Thanks,
Bruno.

**Comment by agiegg** [comment]
Thanks :)
