### ISSUE TITLE
[Bug]: Start-AMBACleanup is not removing role assignment 

### ISSUE THREAD

**Issue by anwather** [Azure/azure-monitor-baseline-alerts#42]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I think that the Start-AMBACleanup script isn't removing the role assignments - it is leaving these orphaned roles.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/11281622/84eea49a-b38d-47ae-93b1-7a509c522d92)
At the management group levels underneath this there is the same thing as well - one for each of identity/management/connectivity management groups e.g.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/11281622/0d78fbdd-7bea-4e38-87bd-269461eefc00)

I noticed this due to attempting to deploy the solution multiple times and it not being able to deploy the role assignments again (said it was unable to update them)

**Comment by arjenhuitema** [comment]
Thank you @anwather for raising this issue. I will add this to our backlog and report here when its been resolved. As a work around, after running the cleanup script you can delete the assignments manually before redeploying.

**Comment by mbrat2005** [comment]
Hi @anwather, thanks for raising this issue! I am working to reproduce what you are seeing so we can get it fixed. The cleanup scripts are written to be conservative in that they delete, so slight changes to the environment might mean the cleanup is incomplete. The way that we determine which Role Assignments to clean up with the Start-AMBACleanup script is:

1. Get a list of Policy Assignments with the metadata property '_deployed_by_amba=True'
2. From the list of Policy Assignments, we pull out the Assignment identity's principal ID
3. Query for Role Assignments to each Policy Assignment identity where the Role Assignment's description property is '_deployed_by_amba'

If you happen to have done any of the following, the script will not clean up the Role Assignments:
- Removed the metadata on the Policy Assignment
- Removed the Policy Assignment manually
- Manually changed the Policy Assignment identity and recreated the Role Assignment (such as in the Portal)
- Removed the Role Assignment description

To help troubleshoot, can you please confirm that the role assignments in your screenshot have the description value '_deployed_by_amba'? To see the Description in the Portal, if you navigate to your connectivity Management Group, go to Access Control (IAM), then choose 'Edit Columns' at the top of the screen and check the box next to Description.

**Comment by paulgrimley** [comment]
[heart]         Paul Grimley (HE/HIM) reacted to your message:
________________________________

**Comment by anwather** [comment]
Yes they have that description :)
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/11281622/587ca3b3-ff47-441e-85e5-1174682e6bdb)

Maybe it needs to remove the role assignment first before removing the assignment?

**Comment by arjenhuitema** [comment]
I was able to reproduce the issue and with #44 it was resolved.
