### ISSUE TITLE
[Question/Feedback]: Linked template validation failed

### ISSUE THREAD

**Issue by gerrynicol** [Azure/azure-monitor-baseline-alerts#43]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi All,

I get the following error on the alzArm.json file having taken a forked copy of the code into VS code. The linked template in question is policies.json.

Thanks.

Template validation failed: The template variable 'policySetDefinitionsAll' is not valid: The template function 'managementGroup' is not valid. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.

**Comment by arjenhuitema** [comment]
Thank you for you for raising this issue @gerrynicol. I was able to replicate it, it looks like the validation of the policies.json fails.

> Template validation failed: The template variable 'policySetDefinitionsAll' is not valid: The template function 'managementGroup' is not valid. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.

 However I could still deploy without any problems. Can you confirm that you are able to deploy successfully as well? 

I´ve created a bug report to investigate this. And we will keep you updated here.

**Comment by gerrynicol** [comment]
@arjenhuitema. Yes, I am still able to deploy through the alernative methosd of using Template Specs.
