### ISSUE TITLE
[General workload issue]: Start-AMBARemediation Script Error `No policy assignments found for policy at management group scope`

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-monitor-baseline-alerts#431]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

After deploying the Azure Monitor Baseline Alerts using the [Deploy with GitHub Actions](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Deploy-with-GitHub-Actions/) approach into an existing environment (which follows the ALZ pattern exactly), I tried to trigger a remediation using the [Remediate Policies](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/) instructions.

![Image](https://github.com/user-attachments/assets/941aef11-cf15-49f2-aaea-fbf6af526756)

After setting the variable to match the target environment...

```powershell
#Modify the following variables to match your environment
$pseudoRootManagementGroup = "bcgov-managed-lz-forge"
$identityManagementGroup = "bcgov-managed-lz-forge-identity"
$managementManagementGroup = "bcgov-managed-lz-forge-management"
$connectivityManagementGroup = "bcgov-managed-lz-forge-connectivity"
$LZManagementGroup="bcgov-managed-lz-forge-landing-zones"
```

... when running the PowerShell script (as shown), I experienced errors about a `Depth` parameter, and ultimately the error message stating _"No policy assignments found for policy Notification-Assets at management group scope bcgov-managed-lz-forge"_.

> Note: This error occurs for other Policy Initiatives as well.

```powershell
.\patterns\alz\scripts\Start-AMBARemediation.ps1 -managementGroupName $pseudoRootManagementGroup -policyName Notification-Assets
```

**Errors**

```powershell
ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At .\azure-monitor-baseline-alerts\patterns\alz\scripts\Start-AMBARemediation.ps1:87 char:86
+ ... stMethod -Uri $uri -Method GET).Content | ConvertFrom-Json -Depth 100
+                                                                ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Json], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At .\azure-monitor-baseline-alerts\patterns\alz\scripts\Start-AMBARemediation.ps1:94 char:91
+ ... stMethod -Uri $uri -Method GET).Content | ConvertFrom-Json -Depth 100
+                                                                ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Json], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At .\azure-monitor-baseline-alerts\patterns\alz\scripts\Start-AMBARemediation.ps1:99 char:86
+ ... stMethod -Uri $uri -Method GET).Content | ConvertFrom-Json -Depth 100
+                                                                ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Json], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

No policy assignments found for policy Notification-Assets at management group scope bcgov-managed-lz-forge
At .\azure-monitor-baseline-alerts\patterns\alz\scripts\Start-AMBARemediation.ps1:133 char:9
+         throw "No policy assignments found for policy $policyName at  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No policy assig...anaged-lz-forge:String) [], RuntimeException
    + FullyQualifiedErrorId : No policy assignments found for policy Notification-Assets at management group scope bcgov-managed-lz-forge
```

## Validation
When checking the Azure Policy assignments, it shows that the initiatives have actually been associated at the target Management Group level.

![Image](https://github.com/user-attachments/assets/738dc14b-b13f-478b-a138-b7e083055491)

## Additional Information

The initiative assignment ID shows `/providers/microsoft.management/managementgroups/bcgov-managed-lz-forge/providers/microsoft.authorization/policyassignments/deploy-amba-notification`.

The definition ID shows `/providers/Microsoft.Management/managementGroups/bcgov-managed-lz-forge/providers/Microsoft.Authorization/policySetDefinitions/Notification-Assets`.

I wonder if this is an issue with the PowerShell script needing to be updated (at the time of this issue it is 2 months old), or if I've missed something required for the remediation.

**Comment by AErmie** [comment]
Quick update...
My apologizes, I was executing the script in the wrong Windows Terminal window. By default it was using the "default" **Windows PowerShell**, and not the **PowerShell 7**.

![Image](https://github.com/user-attachments/assets/3979ca47-5a90-4add-b9d2-e6448d808366)

**Comment by tagolovina** [comment]
Hello @AErmie, Does the remediation script work? Can we close the issue?

**Comment by AErmie** [comment]
> Hello [@AErmie](https://github.com/AErmie), Does the remediation script work? Can we close the issue?

Yes @tagolovina, the remediation script did work. Thanks.
