### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by Greg-Court** [Azure/azure-monitor-baseline-alerts#437]
https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Customize-Policy-Assignment/

The link [alzArm.param.json](https://github.com/azure/azure-monitor-baseline-alerts/blob/2024-08-30/patterns/alz/alzArm.param.json) is broken

![Image](https://github.com/user-attachments/assets/8fd54b22-6bf8-4e32-b9e5-a796698bedbd)

**Comment by tagolovina** [comment]
Hello @Greg-Court , 
Thank you for the feedback, we will fix it.
