### ISSUE TITLE
[General workload issue]: policies-Network.json contains 'Category' (uppercase) resulting in 'unknown' category

### ISSUE THREAD

**Issue by donk-msft** [Azure/azure-monitor-baseline-alerts#443]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

The ALZ pattern Policy Set 'policies-Network.json' contains multiple lines where 'Category' with uppercase C is used. This leads to Policy Definitions with unknown category '--' in the Portal when deployed (Deploy via the Azure Portal (Preview).

![Image](https://github.com/user-attachments/assets/50d042eb-2029-4366-8914-96243a4433c8)

**Comment by Brunoga-MS** [comment]
Hello @donk-msft ,
thanks for your feedback. We have it added to our backlog and it will get fixed as priority.

Thanks,
Bruno.
