### ISSUE TITLE
[General workload issue]:Deploying only Hybrid will fail due to Management Group ID mismatch

### ISSUE THREAD

**Issue by stevedistef** [Azure/azure-monitor-baseline-alerts#459]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

I deployed the new Hybrid policy for use with Arc enabled VMs and I had previously enabled Service Health so it was not a full ALZ deployment.   I tried to deploy ONLY the Hybrid policy via portal.  I specified my Management Group [“Identity”] in all 3 places which asked for that parameter.
 ![Image](https://github.com/user-attachments/assets/d0beab23-d9c7-4c70-8693-b1298259211c)

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "NotFound",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"ManagementGroupNotFound\",\r\n    \"message\": \"The management group 'contoso-management' cannot be found.\"\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by Brunoga-MS** [comment]
Hello @stevedistef ,
thanks for you feedback. I will investigate on this and let you about the finding.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
hello @stevedistef ,
I was able to identify the issue in a wrong MG assignment condition. I will work on the fix which will be included in the next release.

Thanks,
Bruno.

**Comment by stevedistef** [comment]
Sei il migliore!
