### ISSUE TITLE
[General workload issue]: AMBA-ALZ Monitor Alert Approach how to change in code to Centralized?

### ISSUE THREAD

**Issue by kosickimi** [Azure/azure-monitor-baseline-alerts#462]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Question

### Description

Hi,
I see that as default is is decentralized.
AMBA-ALZ Monitor Alert Approach how to change in code to Centralized?
Best regards,
Michal

**Comment by Brunoga-MS** [comment]
Hello @kosickimi ,
thanks for you feedback. Could you please expand a bit on what do you mean by change in code to Centralized?

Thanks,
Bruno.

**Comment by kosickimi** [comment]
Hi @Brunoga-MS 
In documentation I found:
"AMBA-ALZ Monitor Alert Approach
The strategy for enabling alerts in the AMBA-ALZ pattern involves using Azure Policy to deploy alerts as resources are created, configuring action groups, and using Alert Processing Rules to activate alerts and link them to the action group.

There are two main approaches to enabling alerting in the AMBA-ALZ pattern:

**Centralized**
In a centralized alerting approach, a single Action Group is used for all alerts, resulting in a unified alerting email (distribution group) address or other configured actions.

Metric alerts are deployed with resources in the same resource group, while platform alerts like Service Health and Activity are created in a dedicated resource group within a subscription, typically located in the Management platform management group. A single Alert Action Group in this subscription is configured with a central alerting email address and Alert Processing Rules to enable filters and connect alerts to the Alert Action Group.

For example, in the AMBA-ALZ pattern, a single centralized action group is deployed in the “rg-amba-monitoring-001” resource group within a subscription in the Management platform management group.

**Decentralized**
In a decentralized approach, each subscription has a dedicated Action Group, providing more granular control over how alert notifications are directed. For instance, connectivity/networking alerts for the platform connectivity subscription can be directed to the network operations team.

Metric alerts are deployed with resources in the same resource group, while platform alerts such as Service Health and Activity are created in a dedicated resource group for each subscription. Alert Action Groups are established in each landing zone subscription, allowing different operational areas and landing zone subscriptions to have distinct alerting email addresses (e.g., networking, identity, operations, workloads) or other supported actions. Alert Processing Rules are created to enable filters and connect alerts to the Action Groups.

For example, in the AMBA-ALZ pattern, a graphic representation of the flow is provided below."

**Comment by Brunoga-MS** [comment]
As you found in the documentation, we only provide decentralized approach configuration. Changing to centralized would require many changes at the code level including new parameters, change in the policy that creates the notification assets.

Very difficult to describe. As an alternative you could just exempt the subscriptions you do not want to have the policy applied. However, bear in mind that Alert Processing Rules (APR) can only work on the alerts created for resources in the same subscription as  the APR.

**Comment by kosickimi** [comment]
Thank you very much @Brunoga-MS  all clear
