### ISSUE TITLE
[Question/Feedback]: Alert rules for VMs from Azure Monitor Metrics

### ISSUE THREAD

**Issue by msundman78** [Azure/azure-monitor-baseline-alerts#47]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The AMA agent for Windows VMs now have (Preview) support for sending VM guest performance data to Azure Monitor Metrics instead of the InsightsMetrics table in Log Analytics.

However, the VM alert rules (and Grafana templates) in AMBA is currently only looking in the InsightsMetrics table. We'll we see support for alert rules based on Metrics in AMBA in the near future or would you recommend sticking with Log Analytics based performance logs/metrics for new deployments for some time?

**Comment by msundman78** [comment]
Thanks for your reply Paul. I've read the discussions regarding support for deploying AMA with Policies deployed by ALZ so I understand your point.

I assume if AMA is configured to collect logs to the InsightsMetrics table I should still be able to use AMA together with the default AMBA VM Monitoring alerts though, right? I've just finished my Bicep templates for manually deploying AMA to my VMs and DCRs for collecting metrics into InsightsMetrics LAW and will start looking at the alert rules part now, so I'll know soon :)

**Comment by Alboroni** [comment]
For the time being we are sticking to Log Alerts as we can scope the alerts to the subscription and work across region with a single alert. VM insights gives us a std performance collection across all supported VMs  and yes you should be able to use the AMBA VM monitoring alerts with AMA enabled with vm insights as you are doing.

**Comment by Brunoga-MS** [comment]
Hello there,
I would also like to add that VM Insights collects information from the guest point of view, whilst Metrics are from the Virtual Machine Host side. With that in mind, as far as the VM monitoring goes, I would consider the VM Insights more reliable.

**Comment by msundman78** [comment]
> Hello there,
> I would also like to add that VM Insights collects information from the guest point of view, whilst Metrics are from the Virtual Machine Host side. With that in mind, as far as the VM monitoring goes, I would consider the VM Insights more reliable.

I’m talking about the preview functionality of the AMA guest agent which now have the capability to send the guest level metrics to “Metrics”.

**Comment by Brunoga-MS** [comment]
Hello @msundman78,
I got your point. You can certainly use Azure Monitor Metrics (preview) to create your alerts but this is not a scenario we offer at the moment.
