### ISSUE TITLE
Question about AMBA "App" Resources Deployed?

### ISSUE THREAD

**Issue by andrewatfornax** [Azure/azure-monitor-baseline-alerts#471]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

I have noticed that after deploying AMBA, there are two "App" level role assignments at the main management group level at which we are deploying:

![Image](https://github.com/user-attachments/assets/44d275a3-893c-49d7-b062-0132def592cb)

I'm not clear where these "App" resources exist - I don't see them as App Registrations in Entra ID.

Is there somewhere I can find more information about these?

Thanks!

**Comment by Brunoga-MS** [comment]
Hello @andrewatfornax ,
thanks for your question. The "App" you see in the role assignments correspond to System Assigned Managed Identities existing at the tenant level. If you search for "Deploy-AMBA" from the Azure portal you will get all of them:

![Image](https://github.com/user-attachments/assets/35b47363-ef1b-4dba-a1d5-931ee591ab73)

Moreover, they are also visible as "Enterprise Applications" in **_Microsoft Entra ID_** . You need to change the filter to show Managed Identities:

![Image](https://github.com/user-attachments/assets/678a3dd1-b629-4666-83d9-84d2b174b75a)

Let me know if you need more clarifications.

Thanks,
Bruno.

**Comment by andrewatfornax** [comment]
Ah! Perfect, thanks - I wasn't change the Enterprise Application "Application Type", which is why I could not find them.
