### ISSUE TITLE
[Question/Feedback]: Customizing baseline for multiple landing zones

### ISSUE THREAD

**Issue by alexeyzolotukhin** [Azure/azure-monitor-baseline-alerts#50]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello team.

I would like to understand whether AMBA is designed to be a one-time solution that is primarily used to jump start baseline monitoring for a project or is it more like ALZ pattern where users are encouraged to keep their deployment in-sync with the main GitHub repo through the use of provided scripts. 

If it is the later, then what is the thinking on multi-team environments, with multiple landing zones, where there may be a need to customize baseline alerts? For example I have two landing zones for two dev teams, and team #2 needs to update some alert thresholds because for their use case the baseline threshold is too low and they get a lot of false-positives. Do they go ahead and modify their alerts directly in the portal? That would mean that they very quickly deviate from main and risk loosing their changes if the baseline is reapplied. Or is there another pattern they can use?

Thank you :)

**Comment by JoeyBarnes** [comment]
As of today, there isn't any kind of configuration drift capabilities built into AMBA, so it is a one-time solution to jump start baseline monitoring.  That being said, we are actively exploring options that will allow you to compare your deployed alerts with the baseline to see if you have drifted from the baseline recommendations.
