### ISSUE TITLE
[Question/Feedback]: Action groups with other than email for distribution

### ISSUE THREAD

**Issue by KapitanIglu** [Azure/azure-monitor-baseline-alerts#51]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi, 
first of all I like the whole concept here. I am currently working on implementing it in a bigger scale for my company. 
You stated in the documentation:

> _We may investigate and implement alternative or additional actions in the future (e.g. configure alternate email distribution groups depending on the subscription/service or workload owners/etc.)._

Are you still considering that?
I just wanted to highlight it as a very sought after feature on my site ;)

**Comment by arjenhuitema** [comment]
Hi @KapitanIglu,

Thanks for your feedback. Yes we are, actually, it´s actively being developed. You will soon be able to configure the action group to use other actions like: (Note that this will require an existing EventHub/ Logic App etc.)

- EventHubs
- Logic App
- Webhook
- Secure Webhook

I will leave this issue open and will tag you when these features are merged.

**Comment by gerrynicol** [comment]
On this topic, I am also keen on seeing this developed, so thats great news :). I customised the previous incarnation of the AMBA to use Webhooks which worked well with existing Logic Apps. One other aspect of this that would be benefial is the splittling out of the Action Groups per Alert type. i.e An action group for ResourceHealth, One for ServiceHealth etc. In that way the alerts can then be picked up by specigic Logic Apps.

**Comment by arjenhuitema** [comment]
@alexeyzolotukhin thank you for your feedback. 

More flexibility for action groups and actions is in development and should be available in January. The following actions will be implemented:

1. Web and secure webhook
2. Logic Apps
3. EventHub
4. ARM roles
5. Azure Function
6. Automation Runbook

You could then leverage the functionality in Logic Apps and Event hubs to meet your requirements. This considers that you have an existing Logic App or EventHub, if not you will need to be build them before being able to use them for AMBA. 

- [Stream Azure monitoring data to an event hub or external partner](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/stream-monitoring-data-event-hubs)
- [Customize alert notifications by using Logic Apps](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-logic-apps?tabs=send-email)

Additionally, depending on your RBAC configuration, your could leverage sending notifications to ARM roles. **Note** that as of writing the email is only sent to Microsoft Entra ID user members of the selected role, not to Microsoft Entra groups or service principals. Sending email to groups is coming (I dont have an ETA). 

- [Email Azure Resource Manager](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/action-groups#email-azure-resource-manager)
