### ISSUE TITLE
[Question/Feedback]: The template language expression literal limit exceeded. Limit: '131072' and actual: '131072'.

### ISSUE THREAD

**Issue by NikolaiKleppe** [Azure/azure-monitor-baseline-alerts#62]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi,

We have been adding additional alerts to the solution, specifically ~13 new json policies for `compute/virtualMachines`. 
Seems like we have reached the limit for the final `processPolicySetDefinitionsAll` template/JSON content.

To reproduce we added a new alert (the 14th), as well as new parameters for the new alert in `Deploy-LandingZone-Alerts.json`

Full error:

_ERROR: InvalidTemplate - Deployment template validation failed: 'The template variable 'processPolicySetDefinitionsAll' is not valid: The template language expression literal limit exceeded. Limit: '131072' and actual: '131072'. Please see https://aka.ms/arm-functions for usage details.. Please see https://aka.ms/arm-functions for usage details.'._

This is a limitation in ARM/Bicep and is discussed here as well https://github.com/Azure/bicep/issues/4293 _("Increase MaxLiteralCharacterLimit for loadTextContent (specifically for non-JSON content)")_

If this is an actual issue and not an error on my end I suspect this repo will reach this limit soon as well as new alerts are added.

**Comment by arjenhuitema** [comment]
Hi @NikolaiKleppe, thanks for raising this issue. It´s not entirely clear to me where you encounter this issue. Do you receive this error while deploying AMBA, or while building the policy.json from the policy.bicep?

From the error message, it looks like it reached the limit of 131.072 characters of `loadTextContent` somewhere in the policies.bicep, could you try to replace `loadTextContent` in the line that references the PolicySetDefinition that was modified with `string(loadJsonContent('../policySetDefinitions/<name of the json>'))`

`loadJsonContent` has a limit of 1.048.576 characters which should help loading bigger json files. https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-files#loadjsoncontent

You also mention that you modified the Deploy-LandingZone-Alerts.json This is already using the `loadJsonContent`. If the above didn't help, or if it already was configured with `loadJsonContent`, can you share your fork/branch where you made these changes?

Thanks,

Arjen

**Comment by NikolaiKleppe** [comment]
Hi @arjenhuitema, thanks for the details

We receive this error while deploying AMBA. Building the policy.json file works fine.

As you mentioned Deploy-LandingZone-Alerts.json  already uses the `loadJsonContent` - However I tried changing the rest as well and same error.

To me it seems like it's the final result of the `processPolicySetDefinitionsAll` that is too big. 

I created a fork [here, in branch "changes_only" ](https://github.com/NikolaiKleppe/azure-monitor-baseline-alerts/tree/changes_only)  ([commit](https://github.com/NikolaiKleppe/azure-monitor-baseline-alerts/commit/2fa022377c004dcd65627579a40f612bfcba391b)) with the updates, but if you are looking to deploy it you need to copy the new policies and the parameters as our version has new dependencies managed outside AMBA - Also it's based on release [2023-09-28](https://github.com/Azure/azure-monitor-baseline-alerts/releases/tag/2023-09-28)

**Comment by NikolaiKleppe** [comment]
Hi @Brunoga-MS,

Yep no problem. 

Though it might be a quicker test to duplicate one of the existing policies ~20 times and apply that - Unless you've tested that already and found no errors?

**Comment by Brunoga-MS** [comment]
Hello @NikolaiKleppe ,
just wanted to give the update that I am still investigating and working on this issue. I was able to add more than 20 policies but really depends on the size of the policy file and references which is influenced by the number of parameters. I am still looking at a way to not hit the limits.

Will keep you updated.

Thanks,
Bruno.

**Comment by Brunoga-MS** [comment]
Hello @NikolaiKleppe ,
after a long investigation, we haven't found any good way to overcome that limitation. The only reasonable solution for now is to create additional policySetDefinitions to include new policies. Because of that I am going to close this long running one even if not resolved. Sorry about the inconvenience.

Thanks,
Bruno.
