### ISSUE TITLE
[Question/Feedback]: Several Policies became Non Compliant since 10/3 with reason - NoRegisteredProviderFound

### ISSUE THREAD

**Issue by stdistef** [Azure/azure-monitor-baseline-alerts#69]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I initially deployed AMBA from the now Archived repository on 10/3/2023.  I deployed unaligned and deployed all Initiatives, into an existing environment and all Policy definitions were successfully remediated and all Initiatives showed 100% compliant and all ALert Rules were created.

My customer and I have both since experienced the following.  Several Initiatives now have definitions which appear as non-compliant, but the Alert rules are still in place, and they still work (ex, deleting an NSG raises the alert).   However, the dashboard shows non-compliant for these shown.  And the two environments are identical!   And Remediation actually succeeds yet definitions remain reflecting noncompliance.

I am thinking that since we moved AMBA to a new GitHub repo that maybe some of the Bicep templates may have changed, but that doesn't explain why an existing deployed environment that has had no Azure Services added or deleted in the last month suddenly change.     

I don't want to just clean up and start over because this happened to a customer in hos PROD environment, and I want to be certain of the reason why we might suggest that.

Is anyone else seeing this?

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/46e2ec70-b8e8-4343-86db-b12d9bbf32ad)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/9803735c-ad4a-4d6d-94fe-bdce876ff6c4)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/56043cc5-5b6e-4448-8344-f475a9e2eef5)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/4539e836-00d1-4af4-bf9b-23ac70cfe3a5)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/65755baa-8244-4e71-857f-89feab8d3fb2)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/21f0be7f-4207-431d-b6e0-9093a55cb6e4)

This Compliance Reason is the same for all of them across all initiatives....
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/b57d7d18-9570-4557-9380-08b74c74a81f)

This shows I remediated the NSG policy definitions SUCCESSFULLY, yet an hour later they are still showing non-compliant.
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/a0510f7f-9b26-4f8c-b071-e55da9ffbcaf)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/2f0001ef-7917-4885-a89a-e08a14a21069)

![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/4243cc3f-9aa9-4ad1-9aa7-f1c55ce9d1d4)

**Comment by stdistef** [comment]
I have check that both RPs are enabled on my Subscription  
"6. For the policies to work, the following Azure resource providers, normally registered by default, must be registered on all subscriptions in scope:
Microsoft.AlertsManagement
Microsoft.Insights"

**Comment by JustinMendon11** [comment]
Experiencing the exact same issue. Deployed AMBA, all of them went compliant and deployed all the rules and alert rules and now the exact same rules that are showing non-compliant for you is the same for us and the alerts still work. We've deployed this for two customers facing the same compliance issue so any help would be appreciated.

**Comment by Brunoga-MS** [comment]
Hello @stdistef,
Can we have a look at your environment?

**Comment by Brunoga-MS** [comment]
We were able to see and repro this issue that seems to impacting only Activity Log based alerts. We're still actively investigating and get back as soon as possible.

**Comment by philrice** [comment]
@Brunoga-MS  I have been having the same issue and trying to work out why, but am yet to pinpoint it. I did spot though that in a number of policy definitions, there are entries for  "existenceScope": "resourcegroup" and "resourcegroup" (with lowercase G) get flags as invalid input as it requires "resourceGroup" . May or may not be related to the issue, but might be something that is worth correcting if not

**Comment by Brunoga-MS** [comment]
Hello @philrice ,
thanks for the interesting clue. I tried it out with no luck. We're still investigating the issue.

Thanks.

**Comment by Brunoga-MS** [comment]
Policy team have identified the issue and are looking to apply a fix.

**Comment by stdistef** [comment]
just for clarity.  Both my customer and myself both originally deployed AMBA ~10/3 and all Policies that should be compliant, were compliant.   It seems that approximately 11/3 or 11/4 (2 weekends ago) the Activity Log based initiatives all became non compliant.  They have remained this way since.    The alerts still work.   But the Policy compliance portal says non-compliant.

**Comment by stdistef** [comment]
I have been informed that a fix should be rolled out to all regions in the next 24 hours.
Anyone who sees the problem can check as I plan to do tomorrow.

**Comment by philrice** [comment]
@stdistef - so is that in the form of a fix to the Azure Policy platform itself? or are changes being made to the AMBA repo that we will need to resynch with? (or both) 
thanks

**Comment by stdistef** [comment]
> @stdistef - so is that in the form of a fix to the Azure Policy platform itself? or are changes being made to the AMBA repo that we will need to resynch with? (or both) thanks

I am told its an Azure backend service change and wont require us to redeploy.

**Comment by paulgrimley** [comment]
Correct this is a backend issue which is being surfaced by AMBA, no updates are required to your deployment to fix this, we just need to wait for the rollout to complete, if it’s still the same tomorrow please let us know here. Thanks!

**Comment by philrice** [comment]
I am still getting this error , so wanted to check if anyone has seen the changes remediate the problem in their tenant/s yet?
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/1413098/71d7cfb4-ad5e-4235-9c30-54bb6d98e96c)

N.B. - this is a developer tenant im testing in , so it potentially is earmarked to receive updates later than prod tenants, hence the reason for checking / asking

**Comment by JustinMendon11** [comment]
I'm still in the same boat too, @philrice not compliant ones still around at the moment
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/124177767/22d4ddcf-50a8-4bd3-a313-0e33a4b61559)

**Comment by paulgrimley** [comment]
Thanks for sharing, we have been advised the roll-out will complete to all regions by end of Saturday, keep us posted after this date to see if these have landed in your region successfully

**Comment by stdistef** [comment]
My test environment is looking so much better this morning!!!! 
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/edfb7077-509a-41e8-88b9-b96199d8beb0)

**Comment by stdistef** [comment]
Customer's environment in Australia SE, not yet   
![image](https://github.com/Azure/azure-monitor-baseline-alerts/assets/35927980/9bc432a1-0efd-4743-8a9d-b7af1218a6c0)

**Comment by Brunoga-MS** [comment]
Got the news that the issue have been mitigated by the Azure Policy team. You should now see the compliance back to work. My environment looks good now.
