### ISSUE TITLE
[Question/Feedback]: 

### ISSUE THREAD

**Issue by MohmadEh** [Azure/azure-monitor-baseline-alerts#76]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I have noticed a Storage Availability Alert but I was also noticing that is there no Storage Delete Alert which can be activated as in 

https://[azure.github.io/azure-monitor-baseline-alerts/services/KeyVault/vaults/Deploy-ActivityLog-KeyVault-Del.json](https://azure.github.io/azure-monitor-baseline-alerts/services/KeyVault/vaults/Deploy-ActivityLog-KeyVault-Del.json)

**Comment by paulgrimley** [comment]
Hi @MohmadEh acknowledging your ask, we have captured this on the backlog for future planning - no ETA as of yet, if others want to upvote please feel welcome to comment
