### ISSUE TITLE
[Feedback]: Deploy PIP VIP Availability Alert - Only for Standard SKU Public IP Addresses

### ISSUE THREAD

**Issue by teemukom** [Azure/azure-monitor-baseline-alerts#80]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

https://github.com/Azure/azure-monitor-baseline-alerts/blob/main/services/Network/publicIPAddresses/Deploy-PIP-VIPAvailability-Alert.json

"VipAvailability" metric is only available on the Standard SKU. The policyRule should be:
```
   "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Network/publicIPAddresses"
          },
          {
            "field": "Microsoft.Network/publicIPAddresses/sku.name",
            "equals": "Standard"
          },
          {
            "field": "[[concat('tags[', parameters('MonitorDisable'), ']')]",
            "notEquals": "true"
          }
        ]
     }
```

**Comment by paulgrimley** [comment]
@teemukom thank you for this suggestion, do you want to submit a PR to contribute directly and we will review?

**Comment by Brunoga-MS** [comment]
Hello @teemukom ,
your PR has been reviewed and incorporated into a bigger one that will be completed soon. Thanks once again for your suggestion and for your willingness to help.

**Comment by Brunoga-MS** [comment]
Closed since required changes have been addressed as part or [PR 111](https://github.com/Azure/azure-monitor-baseline-alerts/pull/111)
