### ISSUE TITLE
MissingSubscription

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/azure-monitor-baseline-alerts#93]
Hi,

I'm getting an error message after running command
I'm user access administrator and owner on subscription

3. Create a new role assignment by subscription and object. By default, the role assignment will be tied to your default subscription. Replace $subscriptionId with your subscription ID, $resourceGroupName with your resource group name, and $assigneeObjectId with generated assignee-object-id (the newly created service principal object id).

$ az role assignment create --role contributor --subscription xxxxxxxxxxxxxxxxx --assignee-object-id xxxxxxxxxxxxxxxxxxxxxxxxx --assignee-principal-type ServicePrincipal --scope /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-tst-mgt-mon-amba-01

(MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
Code: MissingSubscription
Message: The request did not have a subscription or a valid tenant level resource provider.

**Comment by Brunoga-MS** [comment]
Hello @jerrolmossel,
in our deployment and as per our deployment guide, we do not create any new role. We just do built-in role assignment as you can see in the documentation at [Azure Monitor Baseline Alserts](https://aka.ms/amba).

Could you please clarify which part of the documentation you are following and what goal are you trying to achieve.

Thanks.

**Comment by jerrolmossel** [comment]
Hi @Brunoga-MS 

3. Configure and run the workflow
First, configure your OpenID Connect as described [here](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-openid-connect).

Use the Azure login action with OpenID Connect

Create a Microsoft Entra application and service principal
Using Azure CLI

**Comment by Brunoga-MS** [comment]
Hi @jerrolmossel,
thanks for pointing me to the right direction. You seem to have issue with some prerequisites that falls outside of AMBA documentation and support (they are part of Microsoft Docs). However, I tried to run that part and was successful. The only think I noted is that the you need to pass the ObjectId of the Enterprise Application and not the one of Application Registration during execution of command at step 3 as per your first message.

Let me know if that helps.

**Comment by jerrolmossel** [comment]
Hi @Brunoga-MS 

I managed to create it via Azure portal. First I had dive into the subject app registrations versus enterprise applications for good understanding.

After this works I will try it again with cli or ps. 
Thank you for so far.
